BP of 6.5.X docs REST API to 6.0.X
couchbase/docs-server pull request #1400
Opened 2020-07-08 20:04 UTC by jon-strabala

This is a BP of 6.5.X docs REST API to 6.0.X (the last 6.5 update was https://github.com/couchbase/docs-server/pull/1393)

Essentially 6.0 does not support pause/resume all other functions including stats were tested on 6.0.4 to ensure correctness

Some text needs to differ because of lack of Pause/Resume in 6.0.X "deployment_status (deplyed/undeployed) and processing_status (they must match in 6.0)"

2020-07-13 23:06 UTC, amarantha-k requested changes
@jon-strabala This PR needs a few editorial fixes.

2020-07-13 23:06 UTC, amarantha-k commented on modules/eventing/pages/eventing-api.adoc
> +Retruns the information for one function Functions in the cluster.
typo: Returns

2020-07-13 23:06 UTC, amarantha-k commented on modules/eventing/pages/eventing-api.adoc
> +Note you must always specify deployment_status (deplyed/undeployed) and processing_status (they must match in 6.0) when using this REST endpoint to opdate any option(s).
typo: opdate -> update

2020-07-13 23:06 UTC, amarantha-k commented on modules/eventing/pages/eventing-api.adoc
> +Updates an undeployed a Function with the provided settings. Do not update settings for a deployed.
Remove extra article: "Updates an undeployed Function with..."
Fix incomplete sentence: "Do not update settings for a deployed Function"

2020-07-13 23:06 UTC, amarantha-k commented on modules/eventing/pages/eventing-api.adoc
> +Note you must always specify deployment_status (deplyed/undeployed) and processing_status (they must match in 6.0) when using this REST endpoint to opdate any option(s).
Update: "Note that you..."

2020-07-13 23:06 UTC, amarantha-k commented on modules/eventing/pages/eventing-api.adoc
> +This will return the the subset of statistics for the node.
Fix duplicate article: "...return the subset..."

2020-07-13 23:06 UTC, amarantha-k commented on modules/eventing/pages/eventing-api.adoc
> +This will return the the subset of statistics for the node.
Fix duplicate article: "...return the subset..."

2020-07-13 23:06 UTC, amarantha-k commented on modules/eventing/pages/eventing-api.adoc
> +This will return the the subset of statistics for the node.
Fix duplicate article: "...return the subset..."

2020-07-13 23:06 UTC, amarantha-k commented on modules/eventing/pages/eventing-api.adoc
> +This will return the full statistics set inclusive of events processing, events remaining, execution, failure, latency, worker PIDs and sequence processed.
Add a comma: "...worker PIDs, and sequence processed."

2020-07-13 23:06 UTC, amarantha-k commented on modules/eventing/pages/eventing-api.adoc
> +Note, omitting the parameter type=full will exclude dcp_event_backlog_per_vb, doc_timer_debug_stats, latency_stats, plasma_stats and seqs_processed from the response.
Update: "Note that omitting..."

2020-07-13 23:36 UTC, jon-strabala reviewed
Amaratha, you fixes to my poor spelling look good, however could you look for similar on the 6.5.0 tree the two pages are not identical due to pause/resume.

2020-07-13 23:49 UTC, amarantha-k commented
@jon-strabala Sure - I'll take a look at the 6.5 branch.

2020-08-05 23:35 UTC, amarantha-k approved these changes

2020-08-05 23:53 UTC, merged