Eventing docs updates for 6.5
couchbase/docs-server pull request #1477
Opened 2020-08-10 13:35 UTC by amarantha-k

2020-08-11 13:57 UTC, simon-dew requested changes
LGTM overall, some minor suggestions.

2020-08-11 13:57 UTC, simon-dew commented on modules/eventing/pages/eventing-faq.adoc
> +* Can I Cancel a Timer
```suggestion
* Can I cancel a timer? 
```

Question and title case for consistency

2020-08-11 13:57 UTC, simon-dew commented on modules/eventing/pages/eventing-faq.adoc
> +* Can I create a Recurring timer
```suggestion
* Can I create a Recurring timer?
```

Question for consistency

2020-08-11 13:57 UTC, simon-dew commented on modules/eventing/pages/eventing-faq.adoc
> +* Can I schedule Timer far into the future
```suggestion
* Can I schedule a Timer far into the future?
```

Question for consistency

2020-08-11 13:57 UTC, simon-dew commented on modules/eventing/pages/eventing-faq.adoc
> +* Timer Delays: When I schedule a timer to fire at an exact time, I see some delay why?
```suggestion
* Timer Delays: When I schedule a timer to fire at an exact time, I see some delay. Why?
```

2020-08-11 13:57 UTC, simon-dew commented on modules/eventing/pages/eventing-faq.adoc
>  * How to perform Functions lifecycle operations from CI/CD?
```suggestion
* How do I perform a Function's lifecycle operations from CI/CD?
```

Grammar check

2020-08-11 13:57 UTC, simon-dew commented on modules/eventing/pages/eventing-faq.adoc
> +However keep in mind that sometimes the Function is limited by the overall performance of the Data Service in this case it is appropriate to scale the Data service.
```suggestion
However keep in mind that sometimes the Function is limited by the overall performance of the Data Service. In this case it is appropriate to scale the Data service.
```

2020-08-11 13:57 UTC, simon-dew commented on modules/eventing/pages/eventing-overview.adoc
> +Functions handle and process events that are generated when documents are created, updated, expired or deleted.
```suggestion
Functions handle and process events that are generated when documents are created, updated, expired, or deleted.
```

Oxford comma (style rule)

2020-08-11 13:57 UTC, simon-dew commented on modules/eventing/pages/eventing-overview.adoc
> +* Utilize N1QL queries ot statements form within a Function
```suggestion
* Utilize N1QL queries ot statements form within a Function.
```

Period for consistency with other bullet points.

2020-08-11 13:57 UTC, simon-dew commented on modules/eventing/pages/eventing-overview.adoc
>  Following are a few aspects during the onboarding process:
```suggestion
Following are a few aspects of the onboarding process:
```

2020-08-11 13:57 UTC, simon-dew commented on modules/eventing/pages/eventing-statistics.adoc
> +To fetch Eventing Statistics for a deployed Function you need to leave the Eventing main UI page, first goto the *Couchbase Web Console* > *Servers* page, then click *Statistics.* Note, this page wil
```suggestion
To fetch Eventing Statistics for a deployed Function you need to leave the Eventing main UI page. First go to the *Couchbase Web Console* > *Servers* page, then click *Statistics.* Note that this page will only show deployed Eventing functions. You can scroll down to any section labeled *Eventing Stats: _deployed_function_name_* and expand the section to show the four key graphs for the Function, along with numeric values listed below each graph:
```

Edited slightly for readability

2020-08-11 13:57 UTC, simon-dew commented on modules/eventing/pages/eventing-timers.adoc
> +* reference - This is a unique string that must be passed in to help identify the timer that is being created. References are always scoped to the function and callback they are used with and need to
```suggestion
* reference - This is a unique string that must be passed in to help identify the timer that is being created. References are always scoped to the function and callback they are used with and need to be unique only within this scope. You may not reuse the reference if there is an active timer with the same reference within the current scope. The call returns the reference string if timer was created successfully.  If the reference parameter is set to JavaScript null value, a unique reference will be generated. 
```

Spelling (resue → reuse)

2020-08-11 13:57 UTC, simon-dew commented on modules/eventing/pages/eventing-timers.adoc
> +_Note in release 6.6.0 Eventing Timers can be cancelled using cancelTimer() function, or by creating a new Timer with the same reference as an existing Timer refer to xref:eventing-timers.adoc#limita
```suggestion
_Note that in release 6.6.0 Eventing Timers can be cancelled using the cancelTimer() function, or by creating a new Timer with the same reference as an existing Timer refer to xref:eventing-timers.adoc#limitations[Timers: Limitations]._
```

2020-08-11 13:57 UTC, simon-dew commented on modules/eventing/pages/troubleshooting-best-practices.adoc
> +Typically you shouldn’t configure more than 4 x the number of physical cores (or 2 x # vCPUS) across all your Eventing functions.
```suggestion
Typically you shouldn’t configure more than 4 × the number of physical cores (or 2 × the number of vCPUS) across all your Eventing functions.
```

Minor edits for readability.

2020-08-11 13:57 UTC, simon-dew commented on modules/eventing/pages/eventing-curl-spec.adoc
> +Eventing functions can interact with external systems by using curl function to call their REST API. The possibility to interact with external systems opens a lot of new use cases, such as
```suggestion
Eventing functions can interact with external systems by using the curl() function to call their REST API. The possibility to interact with external systems opens a lot of new use cases, such as:
```

Trying to distinguish between `curl()` (the Eventing function) and `cURL` (the underlying technology).

2020-08-11 13:57 UTC, simon-dew commented on modules/eventing/pages/eventing-curl-spec.adoc
> +* etc..
```suggestion
* etc... 
```

2020-08-11 13:57 UTC, simon-dew commented on modules/eventing/pages/eventing-curl-spec.adoc
> +This feature (introduced in 6.5) is both reliable and secure: the cURL calls are limited to a predefined set of URL bindings, for each binding we can specify authentication, encryption and certificat
```suggestion
This feature (introduced in 6.5) is both reliable and secure: the cURL calls are limited to a predefined set of URL bindings, and for each binding we can specify authentication, encryption, and certificate validation as necessary.  
```

2020-08-11 14:11 UTC, amarantha-k commented
@simon-dew Thanks for the detailed review and suggestions on this large PR. The suggestions have been incorporated.

2020-08-12 09:26 UTC, simon-dew approved these changes

2020-08-12 11:30 UTC, merged