Change default compression setting
couchbase/docs-server pull request #166
Opened 2018-12-03 21:09 UTC by nelio2k

The default is Auto, instead of None.

2018-12-07 16:32 UTC, jamesnocentini requested changes

2018-12-07 16:32 UTC, jamiltz commented on modules/learn/pages/clusters-and-availability/xdcr-advanced-settings.adoc
> +| Defines whether documents are to be compressed for XDCR, and if so, which  compression type is to be used.The default is `Auto`, which will allow compression if both source and target support it.
```suggestion
| Defines whether documents are to be compressed for XDCR, and if so, which compression type is to be used.
The default is `Auto`, which will allow compression if both source and target support it.
```

2018-12-10 02:07 UTC, m123ky79 approved these changes

2019-12-19 21:58 UTC, arod1987 commented
+1

2019-12-19 21:59 UTC, arod1987 approved these changes
+1

2020-04-03 08:53 UTC, tonyjhillman commented
Will be handled by https://github.com/couchbase/docs-server/pull/1188, DOC-6568.

2020-04-03 08:53 UTC, closed without merging