DOC-4522: Added networkUsageLimit parameter to XDCR advanced settings…
couchbase/docs-server pull request #176
Opened 2018-12-04 16:01 UTC by tonyjhillman

… rest api page

2018-12-07 16:29 UTC, jamesnocentini requested changes

2018-12-07 16:29 UTC, jamesnocentini commented on modules/rest-api/pages/rest-xdcr-adv-settings.adoc
> +|==
```suggestion
|===
```

2018-12-10 17:56 UTC, amarantha-k approved these changes

2018-12-17 18:34 UTC, amarantha-k commented
@jamiltz Could you please review & approve the changes? I can't merge unless the change request review is completed.

2019-01-02 10:39 UTC, jamesnocentini approved these changes

2019-01-02 10:56 UTC, merged