DOC-7642d: On-the-wire security for 7.0
couchbase/docs-server pull request #1792
Opened 2021-01-05 12:19 UTC by tonyjhillman

2021-01-06 00:17 UTC, anuthan requested changes

2021-01-06 00:17 UTC, anuthan commented on modules/learn/pages/security/on-the-wire-security.adoc
> +The cluster-wide default value for the minimum TLS version is `tslv1`: this is used by a service if no value has been specified for that service, and no global value has been specified.
Typo, tlsv1

2021-01-06 00:17 UTC, anuthan commented on modules/learn/pages/security/on-the-wire-security.adoc
> +The minimum TLS version can be established either globally or per service as `tlsv1`, `tlsv1.1`, or `tlsv1.2`.
Could you add a few lines on what the minimum tls-version setting means? Like it is done for Cipher-Suite preference below as "This determines ...". 

We should make it clear that minimum tls-version means server will not accept client connections with protocols below this level.

2021-01-06 00:17 UTC, anuthan commented on modules/learn/pages/security/on-the-wire-security.adoc
> +This list can be returned and inspected, as a _read-only_ value.
"can be returned and inspected"
to 
"can be inspected" 
Also, perhaps link to the tab showing how it can be inspected.

2021-01-06 00:17 UTC, anuthan commented on modules/learn/pages/security/on-the-wire-security.adoc
> +Any cipher-suites included in a per-service or global list that do not appear on the pre-configured list of supported cipher-suites for that service are ignored by the service.
This should be after line 79, "The custom list should be a subset of those cipher suites included in the pre-configured list of supported cipher-suites."

2021-01-06 00:17 UTC, anuthan commented on modules/learn/pages/security/on-the-wire-security.adoc
> +* The order of the 1.3 cipher-suites is automatically configured, based on performance characteristics.
Per golang release notes, here https://golang.org/doc/go1.12, "TLS 1.3 cipher suites are not configurable. All supported cipher suites are safe, and if PreferServerCipherSuites is set in Config the preference order is based on the available hardware." 

So let's change it to "The order of the 1.3 cipher-suites is determined based on available hardware"

2021-01-06 00:17 UTC, anuthan commented on modules/manage/pages/manage-security/manage-tls.adoc
> +Specifies the minimum accepted TLS version.
Same comment as the one above about minimum tls version.

2021-01-06 00:17 UTC, anuthan commented on modules/manage/pages/manage-security/manage-tls.adoc
> +The argument must be a list of cipher suites, each of which appears as a member of the array that is the value of  of the non-configurable *supportedCipherSuites* setting for the service.
typo, of of.

2021-01-06 00:17 UTC, anuthan commented on modules/rest-api/pages/rest-setting-security.adoc
> +If the parameter is set for a given service, each listed cipher-suite must appear as a member of the array that is the value of  of the non-configurable *supportedCipherSuites* setting for the servic
Typo, of of

2021-01-06 00:17 UTC, anuthan commented on modules/learn/pages/security/on-the-wire-security.adoc
> +* If no custom list of cipher-suites is established for a given service, and no global list is established, the service uses its pre-configured list of supported cipher-suites.
Upon reading, "By default, Couchbase Server uses a list of HIGH security cipher-suites" in the old doc, https://docs.couchbase.com/server/current/manage/manage-security/manage-tls.html. I was reminded that we still do maintain backward compatibility with it.

Can we change it to the following here and other places where we mention cipher-suites defaults, so that we convey the correct message. 
"If no custom list of cipher-suites is established for a given service, and no global list is established, the service uses a list of HIGH security cipher-suites."

2021-01-06 13:12 UTC, tonyjhillman commented on modules/learn/pages/security/on-the-wire-security.adoc
> +The cluster-wide default value for the minimum TLS version is `tslv1`: this is used by a service if no value has been specified for that service, and no global value has been specified.
Thanks. I've fixed.

2021-01-06 13:15 UTC, tonyjhillman commented on modules/learn/pages/security/on-the-wire-security.adoc
> +The minimum TLS version can be established either globally or per service as `tlsv1`, `tlsv1.1`, or `tlsv1.2`.
I've rewritten as: The minimum TLS version can be established either globally or per service: the server will not accept client connections with protocols below the level of the established, minimum version.

2021-01-06 13:32 UTC, tonyjhillman commented on modules/learn/pages/security/on-the-wire-security.adoc
> +This list can be returned and inspected, as a _read-only_ value.
Have modified, and added a link to the cli example.

2021-01-06 13:33 UTC, tonyjhillman commented on modules/learn/pages/security/on-the-wire-security.adoc
> +Any cipher-suites included in a per-service or global list that do not appear on the pre-configured list of supported cipher-suites for that service are ignored by the service.
Okay, I have moved.

2021-01-06 13:35 UTC, tonyjhillman commented on modules/learn/pages/security/on-the-wire-security.adoc
> +* The order of the 1.3 cipher-suites is automatically configured, based on performance characteristics.
I have changed.

2021-01-06 13:37 UTC, tonyjhillman commented on modules/manage/pages/manage-security/manage-tls.adoc
> +Specifies the minimum accepted TLS version.
I've added.

2021-01-06 13:37 UTC, tonyjhillman commented on modules/manage/pages/manage-security/manage-tls.adoc
> +The argument must be a list of cipher suites, each of which appears as a member of the array that is the value of  of the non-configurable *supportedCipherSuites* setting for the service.
Thanks, have fixed.

2021-01-06 13:38 UTC, tonyjhillman commented on modules/rest-api/pages/rest-setting-security.adoc
> +If the parameter is set for a given service, each listed cipher-suite must appear as a member of the array that is the value of  of the non-configurable *supportedCipherSuites* setting for the servic
Fixed.

2021-01-06 13:42 UTC, tonyjhillman commented on modules/learn/pages/security/on-the-wire-security.adoc
> +* If no custom list of cipher-suites is established for a given service, and no global list is established, the service uses its pre-configured list of supported cipher-suites.
Okay, I can change here. I've tried to make this the explanation to which other passages point, but I'll check through. 

One question: in the old docs, we continued to document the legacy procedure, of setting the custom version of the default list at the command line, and then starting the server. Should we re-include that here?

2021-01-06 18:06 UTC, anuthan commented on modules/learn/pages/security/on-the-wire-security.adoc
> +* If no custom list of cipher-suites is established for a given service, and no global list is established, the service uses its pre-configured list of supported cipher-suites.
Do you mean, https://docs.couchbase.com/server/current/manage/manage-security/manage-tls.html#alternative-cipher-suite-list-configuration ?
Yeah we don't want people using the old style of security setting, better to not include it.

2021-01-06 18:09 UTC, anuthan approved these changes
LGTM

2021-01-07 10:31 UTC, tonyjhillman commented on modules/learn/pages/security/on-the-wire-security.adoc
> +* If no custom list of cipher-suites is established for a given service, and no global list is established, the service uses its pre-configured list of supported cipher-suites.
Ok, thanks - I won't include that.

2021-01-07 10:32 UTC, merged