DOC-8058 operators collections updated.
couchbase/docs-server pull request #1884
Opened 2021-04-02 04:14 UTC by sixthcodebrewer

2021-04-07 03:35 UTC, sixthcodebrewer commented
### Need Help
```
SELECT DISTINCT city FROM `travel-sample`.inventory.landmark AS l
WHERE EXISTS (SELECT city FROM `travel-sample`.inventory.airport AS a );
```
 This query from collectionsops page results in the 626 cities that contain both an airport and a landmark but shows a different result with respect to the ordering of the city with an internal error. 

- Attaching the image of the query and the result 

![query result](https://user-images.githubusercontent.com/48326355/113806326-b9df6c00-977f-11eb-89a3-520ddb6ceabb.png)
![error message](https://user-images.githubusercontent.com/48326355/113806343-be0b8980-977f-11eb-8c47-310853e6f2b4.png)

2021-04-08 20:45 UTC, simon-dew requested changes
Thanks very much for the contribution! Great work. Regarding the query that you flagged as problematic — I'm not sure what this query was trying to do. (Not your fault, I know.) As originally written, the EXISTS expression in this query always returns `true`, which means that the query would just return the 626 distinct cities in the `landmark` collection, even if the subquery didn't generate an error. In fact, it would be much more natural to find the data that this example is supposed to find using a JOIN.

I've therefore made some suggestions to replace this example with a new one using the `hotel` collection. Please note you will also have to update the result for this query — I've added the result as a comment. I couldn't make a suggestion for the query results because you didn't edit this part of the document.

All other changes look good to me 👍

2021-04-08 20:45 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/collectionops.adoc
>  *EXISTS Example 1:* Of the 1641 cities with an airport, search for all cities that have a landmark as well.
```suggestion
*EXISTS Example 1:* Of the 274 cities with a hotel, search for all cities that have hotels with reviews.
```

2021-04-08 20:45 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/collectionops.adoc
> +WHERE EXISTS (SELECT city FROM `travel-sample`.inventory.airport AS a );
```suggestion
SELECT DISTINCT h.city FROM `travel-sample`.inventory.hotel AS h
WHERE EXISTS h.reviews;
```

2021-04-08 20:45 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/collectionops.adoc
>  This results in the 626 cities that contain both an airport and a landmark.
```suggestion
This results in 255 cities that contain hotels with reviews.
```

2021-04-08 20:45 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/collectionops.adoc
>  This results in the 626 cities that contain both an airport and a landmark.
Please also replace the query results (lines 434 to 446) with the updated results:
```
[
  {
    "city": "Medway"
  },
  {
    "city": "Giverny"
  },
  {
    "city": "Glasgow"
  },
  {
    "city": "Highland"
  },
  ```

2021-04-08 22:55 UTC, simon-dew commented
> with an internal error

This is a known issue 😄

2021-04-09 02:38 UTC, sixthcodebrewer commented
> > with an internal error
> 
> This is a known issue

Ok 😃

2021-04-09 02:45 UTC, sixthcodebrewer commented
> Thanks very much for the contribution! Great work. Regarding the query that you flagged as problematic — I'm not sure what this query was trying to do. (Not your fault, I know.) As originally written, the EXISTS expression in this query always returns `true`, which means that the query would just return the 626 distinct cities in the `landmark` collection, even if the subquery didn't generate an error. In fact, it would be much more natural to find the data that this example is supposed to find using a JOIN.
> 
> I've therefore made some suggestions to replace this example with a new one using the `hotel` collection. Please note you will also have to update the result for this query — I've added the result as a comment. I couldn't make a suggestion for the query results because you didn't edit this part of the document.
> 
> All other changes look good to me 

Thank You, Simon, I have committed all the suggested changes.

2021-04-09 09:20 UTC, simon-dew approved these changes
Fantastic, thanks. LGTM 👍

2021-04-09 15:31 UTC, sixthcodebrewer commented
> Fantastic, thanks. LGTM

Thank You 🕺🏻 🙌🏻

2021-04-09 15:52 UTC, merged