DOC-8059 changed n1ql subqueries to support 7.0 version
couchbase/docs-server pull request #1905
Opened 2021-04-15 10:43 UTC by sixthcodebrewer

2021-05-11 03:02 UTC, amarantha-k commented
@simon-dew This is ready for review.

2021-05-14 13:33 UTC, simon-dew requested changes
Thanks for this @sixthcodebrewer! A few points that need addressing: the Q5, Q6 and Q8 examples had not been fully updated, and the running text had not always been updated to reflect the updated examples. I've given full suggestions for these points in the comments.

2021-05-14 13:33 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subqueries.adoc
> +Example Q4: Find the landmark that are named with corresponding city name.
Line 154 above:

```
For example, in the above query <<Q1,Q1>>, the keyspace identifier `pass:c[`travel-sample`]` in the outer query is not considered a variable for the subquery.
```

Please change this to say
```
For example, in the above query <<Q1,Q1>>, the keyspace identifier `pass:c[`travel-sample`.inventory.landmark]` in the outer query is not considered a variable for the subquery.
```

2021-05-14 13:33 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subqueries.adoc
> +Example Q4: Find the landmark that are named with corresponding city name.
```suggestion
Example Q4: Find the landmarks that are named with corresponding city name.
```

2021-05-14 13:33 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subqueries.adoc
>  The reference to `t2` in the subquery is actually referring to the same document from `pass:c[`travel-sample`]` that is being processed as `t1` in the outer query.
```suggestion
The reference to `t2` in the subquery is actually referring to the same document from `pass:c[`travel-sample`.inventory.landmark]` that is being processed as `t1` in the outer query.
```

2021-05-14 13:33 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subqueries.adoc
>  [
Change these results to be the same as the results of Query Q4A below — to emphasize that the queries are equivalent

2021-05-14 13:33 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subqueries.adoc
Please update all the Q5 examples to use `` `travel-sample`.inventory.airport ``:

Example Q5A
```
SELECT count(*) FROM `travel-sample`.inventory.airport t
WHERE (SELECT RAW t.geo.alt FROM t t1)[0] > 6000 ;
```
Example Q5B
```
SELECT count(*) FROM `travel-sample`.inventory.airport t
WHERE (SELECT RAW alt FROM t.geo.alt)[0] > 6000;
```

Example Q5C
```
SELECT count(*) FROM `travel-sample`.inventory.airport t
LET x = t.geo
WHERE (SELECT RAW y.alt FROM x y)[0] > 6000;
```

Example Q5D
```
SELECT count(*) FROM `travel-sample`.inventory.airport t
WHERE (SELECT RAW geo.alt FROM t.geo)[0] > 6000;
```

Please also move the example titles outside of the code blocks and update line 238 so that it reads:

```
In the following equivalent queries, explicit alias `t` of `pass:c[`travel-sample`.inventory.airport]` or LET variable `x` is treated as an expression and hence a nested path like `t.geo.lat` is allowed in the subquery FROM clause.
```

2021-05-14 13:33 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subqueries.adoc
>  That makes the subquery non-correlated by the FROM clause, and the subquery returns all documents from keyspace `pass:c[`travel-sample`]`.
```suggestion
So the `pass:c[`travel-sample`.inventory.airport]` used in the subquery FROM clause is considered a keyspace identifier, but not an expression.
That makes the subquery non-correlated by the FROM clause, and the subquery returns all documents from keyspace `pass:c[`travel-sample`.inventory.airport]`.
```

Please also change line 278 above to read

```
For example, the following example <<Q6,Q6>> has no explicit alias for `pass:c[`travel-sample`.inventory.airport]`.
```

2021-05-14 13:33 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subqueries.adoc
>  FROM `travel-sample` LIMIT 4;
```suggestion
SELECT array_length((SELECT RAW t1.geo.alt
                     FROM `travel-sample`.inventory.airport t1))
FROM `travel-sample`.inventory.airport LIMIT 4;
```

2021-05-14 13:33 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subqueries.adoc
>      "$1": 31596
```suggestion
    "$1": 1968
```

2021-05-14 13:33 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subqueries.adoc
>  FROM `travel-sample` t;
```suggestion
SELECT array_length((SELECT RAW t1.geo.alt FROM t t1))
FROM `travel-sample`.inventory.airport t;
```

2021-05-14 13:33 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subqueries.adoc
>  FROM `travel-sample`;
```suggestion
SELECT array_length((SELECT RAW t1.geo.alt
                     FROM `travel-sample`.inventory.airport))
FROM `travel-sample`.inventory.airport;
```

2021-05-14 13:33 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subqueries.adoc
>      "code": 4020,
Update the results as follows:

```
[
  {
    "code": 4020,
    "msg": "Duplicate subquery alias airport",
    "query": "SELECT array_length((SELECT RAW t1.geo.alt\n                     FROM `travel-sample`.inventory.airport))\nFROM `travel-sample`.inventory.airport;"
  }
]
```

2021-05-14 13:33 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subqueries.adoc
>  In the following example Q6C, the `from-term` has nested path `pass:c[`travel-sample`.geo]` as expression where `pass:c[`travel-sample`]` is referring to the implicit alias of the keyspace in the par
```suggestion
In the following example Q6C, the FROM term has the nested path `airport.geo` as an expression, where `airport` refers to the implicit alias of the keyspace in the parent query.
```

2021-05-14 13:33 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subqueries.adoc
> +//ambigious reference error
You can delete this line 😄

2021-05-14 13:33 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subqueries.adoc
>                       FROM `travel-sample`.geo t1))
```suggestion
SELECT array_length((SELECT RAW t1.alt
                     FROM airport.geo t1))
```

The last element (`airport`) in the nested keyspace identifier is the implicit alias.

2021-05-14 13:33 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subqueries.adoc
> +FROM `travel-sample`.inventory.airport
```suggestion
FROM `travel-sample`.inventory.airport;
```
Add a semicolon for consistency.

So the whole query should read
```
SELECT array_length((SELECT RAW t1.alt
                     FROM airport.geo t1))
FROM `travel-sample`.inventory.airport
```

2021-05-14 13:33 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subqueries.adoc
>  For example, in the following query `pass:c[`beer-sample`]` is not defined in the scope and is treated as a new keyspace identifier.
```suggestion
For example, in the following query `pass:c[`travel-sample`.inventory.hotel]` is not defined in the scope and is treated as a new keyspace identifier.
```

2021-05-14 13:33 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subqueries.adoc
>  The following two queries show valid and invalid examples with `travel-sample` data set.
```suggestion
The following two queries show valid and invalid examples with the `airport` collection.
```

2021-05-14 13:33 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subqueries.adoc
>  FROM `travel-sample` t1
```suggestion
SELECT t1.city, t1.geo.alt
FROM `travel-sample`.inventory.airport t1
```

2021-05-14 13:33 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subqueries.adoc
>        FROM `travel-sample`.geo t2)[0] > 4000;
```suggestion
WHERE (SELECT RAW t2.alt
      FROM airport.geo t2)[0] > 4000;
```

2021-05-14 13:33 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subqueries.adoc
>      "code": 3000,
Update the results to read:
```
[
  {
    "code": 3000,
    "msg": "Ambiguous reference to field airport.",
    "query": "SELECT t1.city, t1.geo.alt\nFROM `travel-sample`.inventory.airport t1\nWHERE (SELECT RAW t2.alt\n      FROM airport.geo t2)[0] > 4000;"
  }
]
```

2021-05-14 13:33 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subqueries.adoc
>  The following example demonstrates the power of using nested path expressions in xref:n1ql-language-reference/correlated-subqueries.adoc[correlated subqueries] over the array subdocument `pass:c[`tra
```suggestion
The following example demonstrates the power of using nested path expressions in xref:n1ql-language-reference/correlated-subqueries.adoc[correlated subqueries] over the array subdocument `hotel.reviews`.
```

2021-05-14 13:33 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subqueries.adoc
>                       WHERE s.ratings.Overall >= 4)[0]
```suggestion
LET cnt_reviewers = (SELECT raw count(*)
                     FROM `travel-sample`.inventory.hotel tmp
                     USE KEYS meta(t).id
                     UNNEST tmp.reviews s
                     WHERE s.ratings.Overall >= 4)[0]
```

2021-05-14 13:33 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subqueries.adoc
>  In Couchbase Server version 4.x the FROM clause of the subquery can only have either keyspace identifier name or a subquery.
```suggestion
The above example Q9A is an equivalent of example <<Q6,Q6>> that does not use nested paths in the subquery FROM clause.
The FROM clause of the subquery can only have either keyspace identifier name or a subquery.
```

Remove references to old versions of the software.

2021-06-04 03:24 UTC, sixthcodebrewer reviewed
@simon-dew  Updated all the suggested changes, Enjoyed Working on this PR. Thank you for helping me out understand the concepts better way. 👐🏻 💯 
Let me know if I have missed something

2021-06-04 03:24 UTC, sixthcodebrewer commented on modules/n1ql/pages/n1ql-language-reference/subqueries.adoc
> +//ambigious reference error
@simon-dew requesting you here to have a look at this query, source#Q6C. 
```
SELECT array_length((SELECT RAW t1.alt
                     FROM `travel-sample`.geo t1))
FROM `travel-sample`.inventory.airport
```
![Screenshot (29)](https://user-images.githubusercontent.com/48326355/117546046-11564d80-b046-11eb-9e69-522cd005818d.png)

2021-06-04 03:24 UTC, sixthcodebrewer commented on modules/n1ql/pages/n1ql-language-reference/subqueries.adoc
> +//ambigious reference error
yes 💯

2021-06-08 12:04 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subqueries.adoc
> +//ambigious reference error
It should be this:
```
SELECT array_length((SELECT RAW t1.alt
                     FROM airport.geo t1))
FROM `travel-sample`.inventory.airport
```

The implicit alias is always the last element in the keyspace path. The keyspace path in the outer query is `` `travel-sample`.inventory.airport ``, so the implicit alias in the inner query is `airport`.

2021-06-11 14:21 UTC, simon-dew requested changes
Thanks for tackling the updates on this page! Sorry for the large number of comments again. Half of these comments are to fix errors with the subquery examples and their results. The other half are just formatting updates.

2021-06-11 14:21 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
Separate the query and the result:

```suggestion
----

.Results
[source,json]
----
```

2021-06-11 14:21 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
> +.Results:
```suggestion

.Results
```

Delete trailing colon `:`

2021-06-11 14:21 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
> +             FROM `travel-sample`.inventory.route s
The source of the subquery should be `route` to correlate with the outer query:

```suggestion
             FROM route.schedule s
```

2021-06-11 14:21 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
> +    "after_10pm": [],
When the subquery is properly correlated with the outer query, it returns the correct results:

```suggestion
    "after_10pm": [
      {
        "day": 2,
        "flight": "AI712",
        "utc": "23:44:00"
      }
    ],
```

2021-06-11 14:21 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
> +    "after_10pm": [],
Again, the results of the subquery should be as follows:

```suggestion
    "after_10pm": [
      {
        "day": 6,
        "flight": "AI588",
        "utc": "22:14:00"
      },
      {
        "day": 5,
        "flight": "AI886",
        "utc": "22:53:00"
      },
      {
        "day": 1,
        "flight": "AI678",
        "utc": "23:50:00"
      }
    ],
```

2021-06-11 14:21 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
> +],
Delete trailing comma

```suggestion
]
```

2021-06-11 14:21 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
>  [source,json]
Query is N1QL

```suggestion
[source,n1ql]
```

2021-06-11 14:21 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
> +            FROM `travel-sample`.inventory.route as s WHERE s.day = 1)[0]  > 4
The source of the suqbuery should be `route` to correlate with the outer query

```suggestion
       FROM route.schedule as s WHERE s.day = 1)[0] > 4
```

2021-06-11 14:21 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
Separate query and results:

```suggestion
----

.Results
[source,json]
----
```

Also update the results! The correct results should be as follows:

``` json
[
  {
    "airline": "AF",
    "sourceairport": "TLV"
  },
  {
    "airline": "AF",
    "sourceairport": "TPE"
  },
  {
    "airline": "AF",
    "sourceairport": "TRI"
  }
]
```

2021-06-11 14:21 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
>  [source,json]
Query is N1QL

```suggestion
[source,n1ql]
```

2021-06-11 14:21 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
Separate query and results

```suggestion
----

.Results
[source,json]
----
```

2021-06-11 14:21 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
>  [source,json]
Query is N1QL

```suggestion
[source,n1ql]
```

2021-06-11 14:21 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
>  RETURNING meta(t).id, t.old_vacancy, t.vacancy;
Separate query and result

```suggestion
RETURNING meta(t).id, t.old_vacancy, t.vacancy;
----

.Results
[source,json]
----
```

2021-06-11 14:21 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
>  [source,json]
Query is N1QL

```suggestion
[source,n1ql]
```

2021-06-11 14:21 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
> +LET x = t
You must include the `geo` field otherwise the query can't find the `alt` sub-field

```suggestion
LET x = t.geo
```

2021-06-11 14:21 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
Include results

```suggestion
.Results
[source,json]
----
[
  {
    "$1": 38
  }
]
----
```

2021-06-11 14:21 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
>  [source,json]
Add explanation of this example. Query is N1QL

```suggestion
In this example, the subquery is not correlated with the parent query, so it returns all of the airports in the `airport` collection.

[source,n1ql]
```

2021-06-11 14:21 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
>  [
Separate query and results

```suggestion
FROM `travel-sample`.inventory.airport LIMIT 4;
----

.Results
[source,json]
----
[
```

2021-06-11 14:21 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
>  [source,json]
Add explanation of this example. Query is N1QL.

```suggestion
In this example, the subquery is correlated with the parent query, so it only returns the single airport found by the parent query.

[source,n1ql]
```

2021-06-11 14:21 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
> +
Separate query and results:

```suggestion
----

.Results
[source,json]
----
```

2021-06-11 14:21 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
>  [source,json]
Query is N1QL

```suggestion
[source,n1ql]
```

2021-06-11 14:21 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
>  RETURNING *;
Consistent uppercase for N1QL commands, and let's return shorter results

```suggestion
UPDATE `travel-sample`.inventory.airport t1 SET airportname_dup = "high_altitude_" || airportname
WHERE  t1.geo.alt IN (SELECT RAW t2.geo.alt
                      FROM `travel-sample`.inventory.airport t2
                      WHERE t2.geo.alt > 6000)
RETURNING t1.airportname_dup;
```

2021-06-11 14:21 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
> +----
```suggestion
.Results
[source,json]
----
[
  {
    "airportname_dup": "high_altitude_Grants Milan Muni"
  },
  {
    "airportname_dup": "high_altitude_Durango La Plata Co"
  },
  {
    "airportname_dup": "high_altitude_Black Rock"
  },
  ...
  {
    "airportname_dup": "high_altitude_Colorado Springs East"
  }
]
----
```

2021-06-11 14:21 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
>  == Example 10
Example 10 is incorrect and also needs results.

``` asciidoc
[source,n1ql]
----
UPDATE `travel-sample`.inventory.airport t1
SET airportname_dup = "high_altitude_2 " || airportname
WHERE (SELECT RAW geo.alt
       FROM t1.geo
       WHERE geo.alt > 6000)[0] = t1.geo.alt
RETURNING t1.airportname_dup;
----

.Results
[source,json]
----
[
  {
    "airportname_dup": "high_altitude_2 Grants Milan Muni"
  },
  {
    "airportname_dup": "high_altitude_2 Durango La Plata Co"
  },
  {
    "airportname_dup": "high_altitude_2 Black Rock"
  },
  ...
  {
    "airportname_dup": "high_altitude_2 Colorado Springs East"
  }
]
----
```

2021-06-11 14:21 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
```suggestion

If you are warned that the query contains no WHERE clause or USE KEYS, choose btn:[Continue].

```

2021-06-11 14:21 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
>  [source,json]
Query is N1QL

```suggestion
[source,n1ql]
```

2021-06-11 14:21 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
> +----
Result is JSON

```suggestion
----

.Results
[source,json]
----
```

2021-06-11 14:21 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
>  ----
This example does not contain a subquery, correlated or otherwise. Replace this entire example code block with a different example from the INSERT page, and include the results. Don't forget that the language of the source code block should be N1QL, not JSON!

``` asciidoc
[source,n1ql]
----
INSERT INTO `travel-sample`.inventory.hotel (KEY UUID()) 
    SELECT x.name, x.city, "landmark_hotels" AS type 
      FROM `travel-sample`.inventory.hotel x
      WHERE x.city WITHIN
        ( SELECT DISTINCT t.city 
            FROM `travel-sample`.inventory.landmark t)
      LIMIT 4
RETURNING *;
----

.Results
[source,json]
----
[
  {
    "hotel": {
      "city": "Aberdeenshire",
      "name": "Castle Hotel",
      "type": "landmark_hotels"
    }
  },
  {
    "hotel": {
      "city": "Aberdeenshire",
      "name": "Two Bears Cottage",
      "type": "landmark_hotels"
    }
  },
  {
    "hotel": {
      "city": "Agoura Hills",
      "name": "Malibu Creek Campground",
      "type": "landmark_hotels"
    }
  },
  {
    "hotel": {
      "city": "Altrincham",
      "name": "Cresta Court Hotel",
      "type": "landmark_hotels"
    }
  }
]
----
```

2021-06-11 14:21 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
>  [source,json]
This query won't do anything because there are no reviews with an overall rating of 0! 1 is the lowest overall rating. First, please change the prose description of this example above to say:

```
A correlated subquery with DELETE.
This example deletes all hotels which got the lowest overall rating from more than 4 reviewers.
```

Then change the language of the query code block to N1QL:

```suggestion
[source,n1ql]
```

2021-06-11 14:21 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
>                            WHERE t2.ratings.Overall = 0 )[0] > 4;
Update the query. Let's also return the hotel name so the user can see what's happened.

```suggestion
DELETE FROM `travel-sample`.inventory.hotel t
WHERE (SELECT RAW count(*)
       FROM t.reviews t2
       WHERE t2.ratings.Overall = 1 )[0] > 4
RETURNING t.name;
```

2021-06-11 14:21 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
>  ----
Finally, show the expected results.

```suggestion
----

.Results
[source,json]
----
[
  {
    "name": "Beverly Laurel Motor Hotel"
  },
  {
    "name": "Tan yr Eglwys Cottages"
  }
]
----
```

2021-06-11 14:21 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
>  ----
First, please add the following admonition _before_ the first Example heading:

``` asciidoc
WARNING: Please note that the examples below will alter the data in your sample buckets.
To restore your sample data, remove and reinstall the `travel-sample` bucket.
Refer to xref:manage:manage-settings/install-sample-buckets.adoc[Sample Buckets] for details.
```

Secondly, please change the language for the first code block to N1QL:

``` asciidoc
[source,n1ql]
```

2021-06-13 07:14 UTC, sixthcodebrewer reviewed
Hey, @simon-dew  Done with all changes. Can you please have a look if we have not missed something 😃

2021-06-13 07:14 UTC, sixthcodebrewer commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
>  == Example 12
@simon-dew this is where I am stuck at. Need your help

2021-06-14 11:50 UTC, simon-dew requested changes
Thanks for the update. Just a handful were missed.

2021-06-14 11:50 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
>  ----
This warning applies to all the examples, not just example 1, so please move the warning to line 3 — _before_ the first Example heading

2021-06-14 11:50 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
>  An example of using same keyspace name in subquery FROM clause that is used in the parent query.
Missed the explanation for this example:

```suggestion
An example of using same keyspace name in subquery FROM clause that is used in the parent query.

In this example, the subquery is not correlated with the parent query, so it returns all of the airports in the `airport` collection.
```

2021-06-14 11:50 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
Missed the note about the warning that the Query Workbench gives you when using the UPDATE command.

2021-06-14 11:50 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
>  RETURNING t1.reviews[*].author, t1.reviews1;
`t1.reviews1` is meaningless. I must have missed this one.

```suggestion
RETURNING t1.reviews[*].author;
```

2021-06-14 11:50 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/subquery-examples.adoc
>  A correlated subquery with DELETE all hotel records which got zero overall rating by more than 4 reviewers.
There are no zero ratings. The minimum is 1.

```suggestion
A correlated subquery with DELETE all hotel records which got the minimum overall rating by more than 4 reviewers.
```

2021-06-14 18:10 UTC, sixthcodebrewer commented
> Thanks for the update. Just a handful were missed.

Yes done 🎉

2021-06-25 12:50 UTC, simon-dew approved these changes

2021-06-25 12:55 UTC, simon-dew requested changes
Thanks for adding the Correlated Subqueries page. Just 3 comments this time.

2021-06-25 12:55 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/correlated-subqueries.adoc
>  Example Q7A: Earlier Q7 rewritten with JOIN
Change this to:

```
Example Q10A: Earlier Q10 rewritten with JOIN
```

2021-06-25 12:55 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/correlated-subqueries.adoc
>        AND route.sourceairport = "SFO"
Change this to

```
WHERE route.sourceairport = "SFO"
```

2021-06-25 12:55 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/correlated-subqueries.adoc
> +[source#Q7A,n1ql]
Change to `[source#Q10A,n1ql]`

2021-06-25 13:18 UTC, simon-dew approved these changes

2021-06-25 13:19 UTC, simon-dew commented
👍 LGTM

2021-06-26 00:04 UTC, merged