DOC-8057 added scopes for array function and bitwise page
couchbase/docs-server pull request #1921
Opened 2021-04-22 16:37 UTC by sixthcodebrewer

2021-04-27 23:09 UTC, simon-dew requested changes
Just a couple of comments to address.

(Incidentally @amarantha-k the document also has examples using the `default` keyspace and the `contacts` keyspace, neither of which exist and which therefore cannot be reproduced. It's outside the scope of this change, but just to note we will probably need a separate effort to deal with examples like this.)

2021-04-27 23:09 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/arrayfun.adoc
> +// this is giving wrong output
Checked and yes, the results given in the doc are wrong. Please update the result on line 189-190 to `"sorted-position": 0` and delete this comment.

2021-04-27 23:09 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/arrayfun.adoc
>  FROM `travel-sample` t
```suggestion
FROM `travel-sample`.inventory.hotel t
```

2021-04-27 23:09 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/arrayfun.adoc
> +.inventory.hotel
```suggestion
```

2021-04-27 23:09 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/arrayfun.adoc
>  LIMIT 1;
So the whole thing should be
```
SELECT ARRAY_PREPEND("Dave Smith",t.public_likes) AS prepend_val
FROM `travel-sample`.inventory.hotel t
LIMIT 1;
```

2021-04-28 15:11 UTC, sixthcodebrewer commented on modules/n1ql/pages/n1ql-language-reference/arrayfun.adoc
> +// this is giving wrong output
thank you changed it

2021-06-08 12:05 UTC, simon-dew approved these changes

2021-06-08 12:14 UTC, simon-dew commented
Made one last minor change myself. 👍 LGTM

2021-06-09 16:33 UTC, merged