DOC-8057 Added the other pages
couchbase/docs-server pull request #2045
Opened 2021-07-12 15:35 UTC by sixthcodebrewer

1. Syntax Check 
2. Added Scopes and Collection for the other Pages

2021-07-14 23:43 UTC, simon-dew requested changes
Thanks for the updates. As usual, I have quite a few requested changes! Sorry about that.

2021-07-14 23:43 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/condfununknown.adoc
> +SELECT IFNULL(null, missing, "abc", 123) AS Mix,
We need the callout number in the code as a target for the callout list under the example. However the callout number should be commented out.

```suggestion
SELECT IFNULL(null, missing, "abc", 123) AS Mix, -- <1>
```

2021-07-14 23:43 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/condfununknown.adoc
> +       IFNULL(missing, missing, missing) AS AllMissing;
We need the callout number in the code as a target for the callout list under the example. However the callout number should be commented out.

```suggestion
       IFNULL(missing, missing, missing) AS AllMissing; -- <2>
```

2021-07-14 23:43 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/curl.adoc
>  ----
Delete this query, and the following results (lines 507-539) — up to (but not including) the line which says "The credentials are required..."

At some point we have to assume no-one is connecting to a Couchbase cluster that's older than 5.0.

2021-07-14 23:43 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/curl.adoc
>    "request" : "POST", "user":"Administrator:password"}).results[*].t  route
We need authentication, but don't need a POST request. The API call falls foul of size limits, so I moved the filter into the CURL statement to restrict the number of records returned by the API call.

```suggestion
   {"data": "statement=SELECT * FROM `travel-sample`.inventory.route t
             WHERE t.sourceairport = 'SFO'",
    "user": "Administrator:password"}).results[*].t route
```

2021-07-14 23:43 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/curl.adoc
>  LIMIT 4;
Moved the filter into the curl statement.
```suggestion
LIMIT 4;
```

So just to check, the complete query should look like this:

```sql
SELECT DISTINCT airline.name, airline.callsign,
   route.destinationairport, route.stops, route.airline
FROM CURL("http://localhost:8093/query/service",
   {"data": "statement=SELECT * FROM `travel-sample`.inventory.route t
             WHERE t.sourceairport = 'SFO'",
    "user": "Administrator:password"}).results[*].t route
JOIN `travel-sample`.inventory.airline
ON KEYS route.airlineid
LIMIT 4;
```

2021-07-14 23:43 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/datefun.adoc
>  ...
ellipsis before the end of the array

```suggestion
...
]
```

2021-07-14 23:43 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/metafun.adoc
>  [source,n1ql]
Please update example 1 to read

```sql
SELECT META() AS metadata
FROM `travel-sample`.inventory.airline
LIMIT 3;
```

2021-07-14 23:43 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/metafun.adoc
>  ----
Please update example 2 to read

```sql
SELECT META().id AS id
FROM `travel-sample`.inventory.airline
LIMIT 3;
```

2021-07-14 23:43 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/patternmatchingfun.adoc
The results for this query should be as follows, with `2`, `1`, `1` for "Th`e` B`a`lmoral G`u`esthouse"

```json
[
  {
    "$1": [
      1,
      1,
      1
    ],
    "name": "Medway Youth Hostel"
  },
  {
    "$1": [
      2,
      1,
      1
    ],
    "name": "The Balmoral Guesthouse"
  }
]
```

2021-07-14 23:43 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/searchfun.adoc
>  [source,json]
Change the two queries in this example to read:

```sql
SELECT META(t1).id
FROM `travel-sample`.inventory.airline AS t1
WHERE SEARCH(t1.country, "+United +States");
```

```sql
SELECT META(t1).id
FROM `travel-sample`.inventory.airline AS t1
WHERE SEARCH(t1, "country:\"United States\"");
```

2021-07-14 23:43 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/searchfun.adoc
>  ]
Change the query in example 2 to read

```sql
SELECT t1.name
FROM `travel-sample`.inventory.hotel AS t1
WHERE SEARCH(t1, {
  "match": "bathrobes",
  "field": "reviews.content",
  "analyzer": "standard"
});
```

Change the query in example 3 to read

```sql
SELECT t1.name
FROM `travel-sample`.inventory.hotel AS t1
WHERE SEARCH(t1, {
  "explain": false,
  "fields": [
     "*"
   ],
   "highlight": {},
   "query": {
     "match": "bathrobes",
     "field": "reviews.content",
     "analyzer": "standard"
   },
   "size" : 5,
   "sort": [
      {
       "by" : "field",
       "field" : "reviews.ratings.Overall",
       "mode" : "max",
       "missing" : "last"
      }
   ]
});
```

2021-07-14 23:43 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/searchfun.adoc
> +WHERE SEARCH(t1.description, "amazing");
May seem counter-intuitive, but it says in the description below, "the query needs to specify the type explicitly". But leave the keyspace as `` `travel-sample`.inventory.hotel ``.

```suggestion
WHERE t1.type = "hotel" AND SEARCH(t1.description, "amazing");
```

2021-07-14 23:43 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/searchfun.adoc
>  ----
You missed all the remaining examples in this page. Please change the queries in example 5, example 6, and example 7 to use `` `travel-sample`.inventory.hotel `` in the FROM clause.

2021-07-14 23:43 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/objectfun.adoc
>  * If [.var]`object` is not an object or NULL, it returns a NULL value object.
Many of these examples will not work with travel-sample out of the box, because they use non-standard data. Please add the following paragraph to the start of this page, after the title but before the first function (OBJECT_ADD).

```asciidoc
If you want to try the examples on this page, you must first run the following query to insert additional data to the `travel-sample` bucket.

WARNING: Please note that the query below will alter the data in your sample buckets.
To restore your sample data, remove and reinstall the `travel-sample` bucket.
Refer to xref:manage:manage-settings/install-sample-buckets.adoc[Sample Buckets] for details.

[source,n1ql]
----
UPDATE `travel-sample`.inventory.route
SET schedule[0] = {"day" : 7, "special_flights": [
                    {"flight": "AI444", "utc": "4:44:44", "codename": "green"},
                    {"flight": "AI333", "utc": "3:33:33"},
                    {"flight": "AI222", "utc": "2:22:22", "codename": "yellow"}
                  ] }
WHERE destinationairport = "CDG" AND sourceairport = "TLV";
----
```

2021-07-14 23:43 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/objectfun.adoc
>  {
Separate query and results

```suggestion
SELECT OBJECT_CONCAT({"abc":1},{"def":2},{"fgh":3});
----

.Results
[source,json]
----
{
```

2021-07-14 23:43 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/objectfun.adoc
> +        ]
Update results

```suggestion
        "name": "special_flights",
        "val": [
          {
            "codename": "green",
            "flight": "AI444",
            "utc": "4:44:44"
          },
          {
            "flight": "AI333",
            "utc": "3:33:33"
          },
          {
            "codename": "yellow",
            "flight": "AI222",
            "utc": "2:22:22"
          }
        ]
```

2021-07-14 23:43 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/objectfun.adoc
> +]
Update results

```suggestion
[
  {
    "$1": [
      [
        "green",
        "yellow"
      ],
      [
        "AI444",
        "AI333",
        "AI222"
      ],
      [
        "4:44:44",
        "3:33:33",
        "2:22:22"
      ]
    ]
  }
]
```

2021-07-14 23:43 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/objectfun.adoc
> +]
Update results

```suggestion
[
  {
    "$1": [
      {
        "name": "codename",
        "val": [
          "green",
          null,
          "yellow"
        ]
      },
      {
        "name": "flight",
        "val": [
          "AI444",
          "AI333",
          "AI222"
        ]
      },
      {
        "name": "utc",
        "val": [
          "4:44:44",
          "3:33:33",
          "2:22:22"
        ]
      }
    ]
  }
]
```

2021-07-14 23:43 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/objectfun.adoc
> +.Example
Seems fine to me!

```suggestion
.Example
```

2021-07-14 23:43 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/objectfun.adoc
>  {
Separate query and request

```suggestion
SELECT OBJECT_REMOVE( {"abc":1,"def":2,"fgh":3},"def");
----

.Results
[source,json]
----
{
```

2021-07-14 23:43 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/objectfun.adoc
>  Changing the metadata field name from "name" to be "new_name"
```suggestion
Changing the `type` field value from "airline" to be "airplane"
```

2021-07-14 23:43 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/objectfun.adoc
>  SELECT object_rename(t, "airline", "airplane")
Wrong function in example!

```suggestion
SELECT object_replace(t, "airline", "airplane")
```

2021-07-14 23:43 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/objectfun.adoc
> +  }
Update results

```suggestion
  {
    "$1": {
      "callsign": "MILE-AIR",
      "country": "United States",
      "iata": "Q5",
      "icao": "MLA",
      "id": 10,
      "name": "40-Mile Air",
      "type": "airplane"
    }
  }
```

2021-07-14 23:43 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/objectfun.adoc
> +]
Update results

```suggestion
[
  {
    "$1": [
      [
        "green",
        null,
        "yellow"
      ],
      [
        "AI444",
        "AI333",
        "AI222"
      ],
      [
        "4:44:44",
        "3:33:33",
        "2:22:22"
      ]
    ]
  }
]
```

2021-07-14 23:43 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/objectfun.adoc
>  Changing the metadata field name from "name" to be "new_name"
It's not metadata

```suggestion
Changing the field name from "name" to be "new_name"
```

2021-07-15 13:40 UTC, simon-dew commented
Not all changes made yet. Will review again when all changes complete.

2021-07-20 20:02 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/patternmatchingfun.adoc
Added note about order of tokens

2021-07-20 20:17 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/objectfun.adoc
>  * If [.var]`object` is not an object or NULL, it returns a NULL value object.
Moved "special flights" update and warning message to top of page

2021-07-20 20:32 UTC, simon-dew approved these changes

2021-07-20 20:34 UTC, simon-dew commented
Took the liberty of making a couple of minor edits. LGTM 👍

2021-07-20 20:43 UTC, amarantha-k commented
Thank you @simon-dew and @sixthcodebrewer!

2021-07-20 20:43 UTC, merged