Sizing updates
couchbase/docs-server pull request #2091
Opened 2021-07-25 15:42 UTC by amarantha-k

2021-07-26 00:01 UTC, westmann requested changes

2021-07-26 00:01 UTC, westmann commented on modules/install/pages/sizing-general.adoc
> +* Ensure that the data space for Analytics node includes replicas.
The Analytics Service currently only replicates metadata, but not the actual data. There is only a small overhead for metadata replicas as metadata is usually small.

2021-07-26 00:01 UTC, westmann commented on modules/install/pages/sizing-general.adoc
> +* When evaluating a query, the Analytic engine makes use of temporary disk space. The type of query being executed can impact the amount of temporary disk space required. For example, a query with he
I'd prefer "Analytics engine" over "Analytic engine" and "uses temporary disk space" over "makes use of temporary disk space".

2021-07-26 00:01 UTC, westmann commented on modules/install/pages/sizing-general.adoc
> +* The percent of data shadowed, which is dependent on your use case.
When ingesting data from the the Data Service into the Analytics Service a filter can be provided that reduces the size of the data that is ingested and also the storage size for the Analytics Service proportionally.

2021-07-26 00:01 UTC, westmann commented on modules/install/pages/sizing-general.adoc
> +Similarly, if a node has 32 virtual cores and was configured with memory >= 16GB, only 16 partitions will be created since the maximum partitions to be automatically created have an upper limit of 16
"only 16 partitions will be created since the maximum partitions to be automatically created have an upper limit of 16 partitions" -> "only 16 partitions will be created as 16 is the upper bound for automatic partitioning"

2021-07-26 00:01 UTC, westmann commented on modules/install/pages/sizing-general.adoc
> +// === Index considerations
The size of a secondary index is approximately the total size of indexed fields in the analytics collection. For example, if a collection has 20 fields and only 1 of those fields appears in the secondary index, the secondary index size will be ~1/20 of the collection size.

2021-07-26 17:24 UTC, amarantha-k commented
@westmann Thank you for the review comments. I've incorporated feedback from here and the shared doc.

2021-07-27 03:56 UTC, amarantha-k commented
The feedback received so far has been incorporated. Merging in prep for GA. Any additional updates will be handled in a separate PR.

2021-07-27 03:56 UTC, merged