DOC-9070: Release Notes for 7.0.1
couchbase/docs-server pull request #2173
Opened 2021-09-01 10:14 UTC by tonyjhillman

2021-09-02 15:59 UTC, amarantha-k commented on modules/release-notes/pages/relnotes.adoc
> +[#release-701]
We list the latest release at the top of the page, so release 7.0.1 should be before 7.0.0

2021-09-02 16:01 UTC, amarantha-k commented on modules/release-notes/pages/relnotes.adoc
> +This section highlights the notable issues fixed in this release.
v7.0 was a major release and hence did not need the fixed issues listed explicitly. For the maintenance releases, we do need to explicitly list the fixed issues. Pls see v6.5.x release notes for reference

2021-09-02 16:01 UTC, amarantha-k requested changes
Added comments on the PR

2021-09-02 17:02 UTC, tonyjhillman commented on modules/release-notes/pages/relnotes.adoc
> +[#release-701]
I"ve changed the order accordingly. Thanks.

2021-09-02 17:02 UTC, tonyjhillman commented on modules/release-notes/pages/relnotes.adoc
> +This section highlights the notable issues fixed in this release.
I've removed the reference to the filter.

2021-09-03 14:55 UTC, ritamcouchbase approved these changes

2021-09-03 14:56 UTC, amarantha-k approved these changes
looks good from editorial perspective. Waiting on QE review/sign-off.

2021-09-03 16:04 UTC, merged

2021-09-03 17:41 UTC, arod1987 reviewed
looks good to me

2021-09-03 17:47 UTC, mihirkamdarcouchbase commented on modules/release-notes/pages/relnotes.adoc
> +| *Summary*: Fixed an error occurring during the refresh of the FTS indexer.
This should be reworded to say something like "Fixed an error occurring when running Flex index queries on a setup that uses alternate addresses"