DOC-9180 Add support for ARM platforms.
couchbase/docs-server pull request #2294
Opened 2021-11-25 10:09 UTC by RayOffiah

2021-12-01 09:27 UTC, b33f requested changes

2021-12-01 09:27 UTC, b33f commented on modules/install/pages/install-platforms.adoc
> +| Linux ARM
Won't it be confusing to say that "Linux ARM" is not supported when Amazon Linux on ARM is supported ? 
IMHO we should remove this note.

2021-12-01 09:27 UTC, b33f commented on modules/install/pages/install-platforms.adoc
> +| Not supported
Couchbase Server is supported on MacOS Apple Silicon (ARM) when using the MacOS Rosetta2 emulation layer.

2021-12-01 18:08 UTC, b33f approved these changes

2021-12-01 18:09 UTC, b33f commented on modules/install/pages/install-platforms.adoc
> +| {empty}
Requires a ARMv8 CPU such as the Amazon Graviton2

2021-12-02 11:18 UTC, b33f approved these changes

2021-12-02 12:07 UTC, simon-dew reviewed
One minor typo I think? LGTM otherwise

2021-12-02 12:07 UTC, simon-dew commented on modules/release-notes/pages/relnotes.adoc
> +* Amazon Linux (ARM )
Looks like a minor typo

```suggestion
* Amazon Linux (ARM)
```

2021-12-02 13:28 UTC, simon-dew approved these changes
LGTM 👍

2022-02-09 09:35 UTC, RayOffiah commented
This is meant for the Neo release, so I'm closing the PR and creating another one for the 7.1 branch

2022-02-09 09:35 UTC, closed without merging

2022-02-09 09:35 UTC, RayOffiah commented
Closing and moving to Neo