DOC-9450: Update SEARCH_META(..) instructions and examples
couchbase/docs-server pull request #2468
Opened 2022-02-17 21:52 UTC by abhinavdangeti

2022-02-18 12:19 UTC, simon-dew commented
I don't see how this PR fixes the broken links mentioned in [DOC-9450](https://issues.couchbase.com/browse/DOC-9450)?

2022-02-18 15:15 UTC, abhinavdangeti commented
@simon-dew One of the links was already fixed previously, as for the other - the page was deleted. So let me push up another patch set overwriting the earlier with the necessary examples.

2022-02-21 05:18 UTC, sreekanth-cb approved these changes

2022-02-21 06:42 UTC, Thejas-bhat commented on modules/fts/pages/fts-searching-from-N1QL.adoc
> +The examples in this page assume that you have a full text search index created with this definition, unless specified otherwise ..
```suggestion
The examples in this page assume that you have a full text search index created with this definition, unless specified otherwise.
```

2022-02-21 06:42 UTC, Thejas-bhat commented on modules/fts/pages/fts-searching-from-N1QL.adoc
> +The above query uses the following index definition ..
```suggestion
The above query uses the following index definition:
```

2022-02-21 06:42 UTC, Thejas-bhat commented on modules/n1ql/pages/n1ql-language-reference/searchfun.adoc
> +The examples in this page assume that you have a full text search index created with this definition, unless specified otherwise ..
```suggestion
The examples in this page assume that you have a full text search index created with this definition, unless specified otherwise.
```

2022-02-21 06:42 UTC, Thejas-bhat commented on modules/n1ql/pages/n1ql-language-reference/searchfun.adoc
> +The above query uses the following index definition ..
```suggestion
The above query uses the following index definition:
```

2022-02-21 06:44 UTC, Thejas-bhat commented
Perhaps, we can have consistent index definition examples wherever possible. This is in reference to index definitions on line 19 and 403 (in [searchfun.adoc](https://github.com/couchbase/docs-server/pull/2469/files#diff-ff88bb5a5507c5ed15fa22bc952475a094f1d4485d008b2501c8eaabeeab7840) and similarly on lines 13 and 395 in [fts-searching-from-N1QL.adoc](https://github.com/couchbase/docs-server/pull/2469/files#diff-d59555c527cac28c5f416b3fdfb9cbdf68861fbae31c47f8272671d64a936ef3)) which differ in sourceType and the segmentVersion specified.

2022-02-22 21:58 UTC, abhinavdangeti commented
> Perhaps, we can have consistent index definition examples wherever possible. This is in reference to index definitions on line 19 and 403 (in [searchfun.adoc](https://github.com/couchbase/docs-server/pull/2469/files#diff-ff88bb5a5507c5ed15fa22bc952475a094f1d4485d008b2501c8eaabeeab7840) and similarly on lines 13 and 395 in [fts-searching-from-N1QL.adoc](https://github.com/couchbase/docs-server/pull/2469/files#diff-d59555c527cac28c5f416b3fdfb9cbdf68861fbae31c47f8272671d64a936ef3)) which differ in sourceType and the segmentVersion specified.

Ya good point, let me update the patchset.

2022-02-23 23:06 UTC, jon-strabala requested changes
Note we previously had fts-demonstration-indexes.adoc which is still in 6.6 it becomes https://docs.couchbase.com/server/6.6/fts/fts-demonstration-indexes.html
the page has been removed in the recent updates.

Perhaps we should put it back as we reference this missing page from two additional documents outside this update which results in dead links

find . -name '*.adoc' -exec  grep -l :fts-demonstration-indexes {} \;

1. ./docs-server/modules/n1ql/pages/n1ql-language-reference/searchfun.adoc
2. ./docs-server/modules/fts/pages/fts-searching-from-N1QL.adoc
3. ./docs-server/modules/fts/pages/fts-quickstart-guide.adoc  
4. ./docs-server/modules/fts/pages/fts-supported-queries-geo-spatial.adoc

Items 1. and 2. are fixed in this PR
Item 3. Is a commented out reference - it should be deleted (it is a false positive via find)
Item 4. requires some minor work on fts-supported-queries-geo-spatial.adoc to remove "See [Demonstration Indexes](https://github.com/couchbase/docs-server/blob/release/7.0/modules/fts/pages/fts-demonstration-indexes.adoc) for the body" as the target no longer exists.

This will still leaves us with potential off site references to the missing page "fts-demonstration-indexes.adoc" but our docs will be consistent.

2022-02-23 23:31 UTC, abhinavdangeti commented
@jon-strabala Let me push up a patch here removing references to `fts-demonstration-indexes`. 

As for adding the dropped page back ..
* I don't believe there's any off site references to it.
* If you think it's justifiable to add it back - we'll need to add to it index definitions that can be built against scope and collections first.
* Also, since it's not part of this ticket - best deal with it separately.

2022-02-24 00:53 UTC, jon-strabala approved these changes
LGTM

2022-02-24 00:58 UTC, merged