DOC-9339: Search UI can support all FTS queries
couchbase/docs-server pull request #2471
Opened 2022-02-18 20:57 UTC by abhinavdangeti

2022-02-21 05:16 UTC, sreekanth-cb approved these changes

2022-02-21 05:46 UTC, RayOffiah requested changes

2022-02-21 05:46 UTC, RayOffiah commented on modules/fts/pages/fts-searching-from-the-UI.adoc
> +NOTE: Any supported query can be executed from the UI - meaning the UI can accept a valid string (query string syntax) or a JSON object conforming to a supported syntax (query or search request). How
```suggestion
NOTE: Any supported query can be executed from the UI, meaning the UI can accept a valid string (query string syntax) or a JSON object conforming to a supported syntax (query or search request). However the resultset will only contain document IDs along with the requested fields and scores (if applicable). Any array positions or facets' results will _NOT_ be displayed.
```

2022-02-21 06:00 UTC, Thejas-bhat approved these changes

2022-02-24 17:32 UTC, jon-strabala approved these changes
LGTM

2022-02-24 17:34 UTC, merged