DOC-9596 document UI updates for udf js
couchbase/docs-server pull request #2537
Opened 2022-03-15 11:43 UTC by RayOffiah

2022-03-23 16:26 UTC, simon-dew requested changes
Thanks Ray, this is great. Just one addition, could you also add a section about the UDF UI (including a link) to the [tools-ref](https://docs.couchbase.com/server/current/tools/tools-ref.html) page? Thanks.

2022-03-23 16:26 UTC, simon-dew commented on modules/tools/pages/udfs-ui.adoc
> +Starting from Version 7.1, the Couchbase Administration console provides a CRUD{empty}footnote:[**CR**eate **U**pdate **D**elete] interface for user defined functions written in {sqlpp} or JavaScript
Doesn't the R in CRUD stand for "read"? 🤔 I would just rephrase this to avoid the acronym:

```suggestion
Starting from Couchbase Server 7.1, the Couchbase Administration console provides an interface to create, update, or delete user-defined functions written in {sqlpp} or JavaScript.
```

2022-03-23 16:26 UTC, simon-dew commented on modules/tools/pages/udfs-ui.adoc
> +:description: The Couchbase Server admin console provides a UI for adding User-defined-functions
Consistent hyphenation — also capitalization, punctuation

```suggestion
:description: The Couchbase Server admin console provides a UI for adding user-defined functions.
```

2022-03-23 16:26 UTC, simon-dew commented on modules/tools/pages/udfs-ui.adoc
> +Start at the administration console and select menu:Query[UDFs] from the menus to access the `UDF` screen:
We use bold text for UI elements. You can add the `[.ui]` role if you want, but it's not necessary, and it does make the source look more cluttered / harder to read.

Also, not actually a style rule, but I'd advise against using a colon at the end of a paragraph before an image. It's just one more thing to change if you ever move the paragraphs or images around, or add an extra paragraph.

```suggestion
Start at the administration console and select menu:Query[UDFs] from the menus to access the *UDF* screen.
```

2022-03-23 16:26 UTC, simon-dew commented on modules/tools/pages/udfs-ui.adoc
> +image::udfs-ui/udfs-screen.png[alt="screen for adding user-defined functions"]
Don't really need the subdirectory? All the other images for this module are in one flat directory

2022-03-23 16:26 UTC, simon-dew commented on modules/tools/pages/udfs-ui.adoc
> +Click on `{plus}{nbsp}add function library` link to create a library of JavaScript functions.
UI element

```suggestion
Click on *{plus}{nbsp}add function library* link to create a library of JavaScript functions. 
```

2022-03-23 16:26 UTC, simon-dew commented on modules/tools/pages/udfs-ui.adoc
> +You can set a `Namespace` for your library which will restrict its access to users that have permissions to access the bucket and scope defined in the Namespace.
UI element

```suggestion
You can set a *Namespace* for your library which will restrict its access to users that have permissions to access the bucket and scope specified by the namespace.
```

2022-03-23 16:26 UTC, simon-dew commented on modules/tools/pages/udfs-ui.adoc
> +Before you leave the screen, you must set a `Library Name`.
UI element

```suggestion
Before you leave the screen, you must set a *Library Name*.
```

2022-03-23 16:26 UTC, simon-dew commented on modules/tools/pages/udfs-ui.adoc
> +Press the btn:[Save] to leave the editor and return to the main UDF screen.
I always like to include the **Cancel** button for completeness. Also, precision — the main purpose of the **Save** button is save the changes, not to leave the editor. 

```suggestion
Click btn:[Save] to save the library and return to the main UDF screen, or btn:[Cancel] to cancel without saving the library.
```

2022-03-23 16:26 UTC, simon-dew commented on modules/tools/pages/udfs-ui.adoc
> +You can also delete the whole library by clicking on the `Drop` link.
UI elements. Capitalization should match UI.

```suggestion
You can *edit* the library again to add and/or delete functions contained inside it. 

You can also delete the whole library by clicking on the *drop* link.
```

2022-03-23 16:26 UTC, simon-dew commented on modules/tools/pages/udfs-ui.adoc
> +You can add your own user-defined functions in the lower `User-Defined Functions` list. These functions can be one of two types:
UI elements, semantic line breaks

```suggestion
You can add your own user-defined functions in the lower *User-Defined Functions* list.
These functions can be one of two types:
```

2022-03-23 16:26 UTC, simon-dew commented on modules/tools/pages/udfs-ui.adoc
> +*Inline*:: This is a function written in {sqlpp} which can be used as part of another {sqlpp} statement (such as xref:n1ql:n1ql-language-reference/selectintro.adoc[`SELECT`] and xref:n1ql:n1ql-langua
Actually tbh I would move this section down to the discussion of the **Function Type** drop-down list. It would be more useful there.

2022-03-23 16:26 UTC, simon-dew commented on modules/tools/pages/udfs-ui.adoc
> +To add a user-defined function, click on `{plus}{nbsp}add function` below the `User-Defined Functions` list.
UI elements

```suggestion
To add a user-defined function, click on *{plus}{nbsp}add function* below the *User-Defined Functions* list.
```

2022-03-23 16:26 UTC, simon-dew commented on modules/tools/pages/udfs-ui.adoc
> +The `Namespace` can be set to define the scope that function resides in (`travel-sample.inventory` for example).
UI elements.

```suggestion
The *Namespace* can be set to define the scope that function resides in (`travel-sample.inventory` for example). 
```

2022-03-23 16:26 UTC, simon-dew commented on modules/tools/pages/udfs-ui.adoc
> +Use any valid identifier as the `Function Name`.
UI elements

```suggestion
Use any valid identifier as the *Function Name*.
```

2022-03-23 16:26 UTC, simon-dew commented on modules/tools/pages/udfs-ui.adoc
> +As noted <<user-defined-functions, above>>, the `Function Type` can be either `inline` or `Javascript`.
UI elements. Also as noted above, I would move the description of Inline and External functions to this point.

```suggestion
As noted <<user-defined-functions, above>>, the *Function Type* can be either `inline` or `Javascript`. 
```

2022-03-23 16:26 UTC, simon-dew commented on modules/tools/pages/udfs-ui.adoc
> +If you switch `Function Type` to `Javascript` then the dialog will change to configure a JavaScript function call:
ui element. Also colon before images.

```suggestion
If you switch *Function Type* to `Javascript` then the dialog will change to configure a JavaScript function call.
```

2022-03-23 16:26 UTC, simon-dew commented on modules/tools/pages/udfs-ui.adoc
> +Then you select the `Javascript Library` where you created your Javascript function, and the name of your function. (There is no need to include the parameters).
ui element, semantic line breaks. Also can you move the information about the **Library Function Name** to its own paragraph.

```suggestion
Then you select the *Javascript Library* where you created your Javascript function, and the name of your function.
(There is no need to include the parameters.)
```

2022-03-23 16:26 UTC, simon-dew commented on modules/tools/pages/udfs-ui.adoc
> +
Can you add a separate paragraphs explicitly describing:

1. The **Library Function Name** box.
2. The **Save Function** button and the **Cancel** button.

2022-03-25 09:32 UTC, RayOffiah commented on modules/tools/pages/udfs-ui.adoc
> +Starting from Version 7.1, the Couchbase Administration console provides a CRUD{empty}footnote:[**CR**eate **U**pdate **D**elete] interface for user defined functions written in {sqlpp} or JavaScript
Yup, stands for Read.
Mustn't write without coffee.

2022-03-25 09:34 UTC, RayOffiah commented on modules/tools/pages/udfs-ui.adoc
> +image::udfs-ui/udfs-screen.png[alt="screen for adding user-defined functions"]
I think the images are better in their own folder that relates to the guide they're being used for. It makes them easier to find. 
I'm going to leave this one.

2022-03-30 04:45 UTC, merged