Update FTS FAQs for diacritic analyzers
couchbase/docs-server pull request #2574
Opened 2022-03-30 13:01 UTC by sreekanth-cb

2022-03-30 13:13 UTC, Thejas-bhat approved these changes

2022-03-30 15:07 UTC, abhinavdangeti commented on modules/fts/pages/fts-troubleshooting.adoc
> +Now, its ready for searching.
Perhaps a mention here about only using **analytic queries** here would do some good.

2022-04-25 08:26 UTC, RayOffiah requested changes
Small punctuation change

2022-04-25 08:26 UTC, RayOffiah commented on modules/fts/pages/fts-troubleshooting.adoc
> +Now, its ready for searching.
```suggestion
Now, it's ready for searching.
```

2022-04-25 08:27 UTC, RayOffiah approved these changes

2022-04-25 08:29 UTC, RayOffiah commented on modules/fts/pages/fts-troubleshooting.adoc
> +Please note this asciifolding character filter is available since 6.5.0 release.
```suggestion
Please note this asciifolding character filter is available since the 6.5.0 release.
```

2022-12-14 01:08 UTC, jon-strabala commented
@RayOffiah Sreekanth Sivasankaran has left Couchbase, I also imagine that is PR applies to 7.1 and also 7.2

2024-09-19 20:36 UTC, merged