Quick clarification about unequal groups
couchbase/docs-server pull request #2877
Opened 2022-08-22 21:34 UTC by BKaneAtWork

2024-10-29 14:04 UTC, BKaneAtWork commented
@couchbase/docs-team please review

2024-11-01 16:24 UTC, simon-dew requested changes

2024-11-01 16:24 UTC, simon-dew commented on modules/learn/pages/clusters-and-availability/groups.adoc
> +In this scenario, the `active balance` and `rack-zone` constraints will take priority:
Spaces at line end?

```suggestion
Not all the constraints can be satisfied when the buckets are allocated across uneven groups.
In this scenario, the `active balance` and `rack-zone` constraints will take priority:
```

2024-11-01 16:26 UTC, simon-dew approved these changes
LGTM 👍

2024-11-01 17:55 UTC, merged

2024-11-01 17:55 UTC, simon-dew commented
Thanks for the contribution!