DOC-10454 N1QL to SQL++ Rebrand for JavaScript UDFs
couchbase/docs-server pull request #2945
Opened 2022-10-06 09:58 UTC by RayOffiah

Added sqlpp attribute
Changes source block language definitions to sqlpp

2022-10-10 12:28 UTC, simon-dew requested changes
Thanks @RayOffiah . Some comments / suggestions

2022-10-10 12:28 UTC, simon-dew commented on modules/guides/pages/create-user-defined-function.adoc
>  == Introduction
This section is empty?

2022-10-10 12:28 UTC, simon-dew commented on modules/guides/pages/create-user-defined-function.adoc
> +You can create an {sqlpp} User-Defined Function by using:
See comments on previous pull request. If we specify that "SQL++" is pronounced "sequel plus plus", we don't have to change the indefinite article.

Google ngram viewer gives [more matches for "a SQL" than "an SQL"](https://books.google.com/ngrams/graph?content=a+SQL%2Can+SQL&year_start=1800&year_end=2019&corpus=26&smoothing=3&direct_url=t1%3B%2Ca%20SQL%3B%2Cc0%3B.t1%3B%2Can%20SQL%3B%2Cc0), especially in recent years.

2022-10-10 12:28 UTC, simon-dew commented on modules/guides/pages/create-user-defined-function.adoc
> +For more information on {sqlpp} User Defined Functions in general, read xref:n1ql:n1ql-language-reference/userfun.adoc[]
Full stop at end?

2022-10-10 12:28 UTC, simon-dew commented on modules/guides/pages/create-user-defined-function.adoc
> +Run a `curl` command from the shell to add an {sqlpp} User-Defined Function that calls your Javascript function.
As above, I think we should leave the indefinite article unchanged; it's one less thing to worry about.

2022-10-10 12:28 UTC, simon-dew commented on modules/guides/pages/create-user-defined-function.adoc
> +Having created your {sqlpp} User-Defined Function, the xref:call-user-defined-function.adoc[next step] is to use an  {sqlpp} statement to call the function.
As above, I think we should leave the indefinite article unchanged; it's one less thing to worry about.

2022-10-10 12:28 UTC, simon-dew commented on modules/javascript-udfs/pages/calling-javascript-from-n1ql.adoc
> +Before you can call a JavaScript function, you must first create a {sqlpp} User-Defined Function it.
To what it? Seem to be some words missing at the end here

```suggestion
Before you can call a JavaScript function, you must first create a {sqlpp} User-Defined Function to call it.
```

2022-10-10 12:28 UTC, simon-dew commented on modules/javascript-udfs/partials/libraries-and-scopes.adoc
> +an *{sqlpp} User-Defined Function* is defined to act a reference caller to the JavaScript function.
Suggest leaving indefinite article unchanged (as above) for ease of conversion and consistency:

```suggestion
a *{sqlpp} User-Defined Function* is defined to act a reference caller to the JavaScript function.
```

2022-10-11 12:39 UTC, simon-dew approved these changes
LGTM 👍 (with comments)

2022-10-11 12:40 UTC, simon-dew commented on modules/javascript-udfs/pages/calling-javascript-from-n1ql.adoc
> +Before you can call a JavaScript function, you must first create a {sqlpp} User-Defined Function it.
Don't think this has been fixed?

2022-10-11 12:41 UTC, simon-dew commented on modules/guides/pages/create-user-defined-function.adoc
>  == Introduction
Don't think this has been fixed?

2022-10-11 12:56 UTC, RayOffiah commented on modules/guides/pages/create-user-defined-function.adoc
>  == Introduction
Mmm. Seems to be okay.

2022-10-11 14:15 UTC, simon-dew commented on modules/guides/pages/create-user-defined-function.adoc
>  == Introduction
My bad 👍

2022-10-11 14:15 UTC, simon-dew approved these changes
LGTM 👍

2022-10-12 09:47 UTC, merged