DOC-10601: Updates to auto-failover REST pages
couchbase/docs-server pull request #2993
Opened 2022-11-10 13:04 UTC by tonyjhillman

2022-11-10 18:24 UTC, neelima32 commented on modules/rest-api/pages/rest-cluster-autofailover-enable.adoc
> +Setting `enabled` to `false` automatically sets `failoverOnDataDiskIssues[enabled]` to `false`.
sets both `failoverOnDataDiskIssues[enabled]` and `canAbortRebalance` to `false`.
(I assume we're referring to `canAbortRebalance` because this is for 7.1, both are deprecated in elixir 7.5.0).

2022-11-10 18:25 UTC, neelima32 commented on modules/rest-api/pages/rest-cluster-autofailover-enable.adoc
> +Note that when `enabled` is set to `false`, the values supplied for any additional parameters (including `failoverOnDataDiskIssues[enabled]`) are ignored.
including `failoverOnDataDiskIssues[enabled]` and `canAbortRebalance`

2022-11-10 18:27 UTC, neelima32 commented on modules/rest-api/pages/rest-cluster-autofailover-enable.adoc
> +The value can be either `true` (the default) or `false`.
This parameter is optional.
This parameter and its values are ignored if the value for the `enabled` parameter is `false`.

2022-11-10 18:32 UTC, neelima32 commented on modules/rest-api/pages/rest-cluster-autofailover-settings.adoc
> +** `enabled`, which indicates whether auto-failover can occur when a disk has been unresponsive, and which can be `true` (the default) or `false`.
and which can be `true` or `false` (the default).

2022-11-10 18:42 UTC, neelima32 commented on modules/rest-api/pages/rest-cluster-autofailover-enable.adoc
> +This parameter and its values are ignored if the value for the `enabled` parameter is `false`.
This parameter is optional.

2022-11-10 18:45 UTC, neelima32 requested changes
Changes look good to me, suggested a few changes inline. Thanks!

2022-11-11 00:11 UTC, tonyjhillman commented on modules/rest-api/pages/rest-cluster-autofailover-enable.adoc
> +Setting `enabled` to `false` automatically sets `failoverOnDataDiskIssues[enabled]` to `false`.
Yes, it's for 7.1 and (I guess) 7.2.

2022-11-11 00:13 UTC, tonyjhillman commented on modules/rest-api/pages/rest-cluster-autofailover-enable.adoc
> +Note that when `enabled` is set to `false`, the values supplied for any additional parameters (including `failoverOnDataDiskIssues[enabled]`) are ignored.
Have included.

2022-11-11 00:14 UTC, tonyjhillman commented on modules/rest-api/pages/rest-cluster-autofailover-enable.adoc
> +The value can be either `true` (the default) or `false`.
Have included.

2022-11-11 00:15 UTC, tonyjhillman commented on modules/rest-api/pages/rest-cluster-autofailover-settings.adoc
> +** `enabled`, which indicates whether auto-failover can occur when a disk has been unresponsive, and which can be `true` (the default) or `false`.
Thanks. Have fixed.

2022-11-11 00:16 UTC, tonyjhillman commented on modules/rest-api/pages/rest-cluster-autofailover-enable.adoc
> +This parameter and its values are ignored if the value for the `enabled` parameter is `false`.
Have included.

2022-11-11 00:16 UTC, tonyjhillman commented
Thanks, I've added these and will merge for 7.1.

2022-11-11 00:16 UTC, merged