Release/7.0 minor fts updates
couchbase/docs-server pull request #3021
Opened 2022-12-13 19:53 UTC by jon-strabala

Similar fixes for 7.0, 7.1, 7.3 (all in seperate PRs)

- dead/removed document/pages
- clarity in documentation
- improve via linking content

2023-02-16 17:46 UTC, sarahlwelton requested changes
Some comments to fix up when you get a chance.

2023-02-16 17:46 UTC, sarahlwelton commented on modules/eventing/pages/eventing-api.adoc
> +Reset an Application's statistics.
I'm confused, is this an Eventing Function or an "application" that we're resetting stats for? It seems to be the same function across the different versions you created for this PR, but the text is different.

2023-02-16 17:46 UTC, sarahlwelton commented on modules/eventing/pages/eventing-api.adoc
> +| [.path]_/resetStatsCounters?appName=[function_name]_
This is a larger question, because I realize that the entire page is like this, but I'm wondering if square brackets are really enough to set off that these need to be replaced with actual values.

2023-02-16 17:46 UTC, sarahlwelton commented on modules/fts/pages/fts-index-analyzers.adoc
> +[#Supported-Languages]
```suggestion
[#Supported-Languages]
=== Supported Analyzer Languages
```

2023-02-16 17:46 UTC, sarahlwelton commented on modules/fts/pages/fts-index-analyzers.adoc
>  Additionally, a range of analyzers is provided for the specific support of certain languages, as shown by the table immediately below.
```suggestion
The Search Service has pre-built analyzers for the following languages:
```

2023-02-16 17:46 UTC, sarahlwelton commented on modules/fts/pages/fts-index-analyzers.adoc
>  .Supported Analyzer Languages
```suggestion

```

2023-02-16 17:46 UTC, sarahlwelton commented on modules/fts/pages/fts-introduction.adoc
> +Full Text Search includes pre-built _text analyzers_ including but not limited to the following languages: Arabic, CJK characters (Chinese, Japanese, and Korean), English, French, Hindi, Italian, Kur
```suggestion
Full Text Search includes pre-built text analyzers for multiple languages. For the current list of all supported languages in Couchbase Server refer to: xref:fts-index-analyzers.adoc#Supported-Languages[Supported Analyzer Languages]
```

2023-02-16 17:46 UTC, sarahlwelton commented on modules/fts/pages/fts-query-string-syntax-field-scoping.adoc
> +Note, the above syntax is a simple and easy way to create xref:fts-supported-queries-compound-query.adoc[Compound Queries] in Search.
```suggestion
TIP: You can use the preceding syntax to create xref:fts-supported-queries-compound-query.adoc[Compound Queries] in Search.
```

2023-02-16 17:46 UTC, sarahlwelton commented on modules/fts/pages/fts-search-request.adoc
>  :page-aliases: fts-queries.adoc
```suggestion
:page-aliases: fts-queries.adoc, fts-consistency.adoc
```

We don't need two of these properties, a comma-separated list is fine.

2023-02-16 17:46 UTC, sarahlwelton commented on modules/fts/pages/fts-search-request.adoc
> +:page-aliases: fts-consistency.adoc
```suggestion

```

2023-02-16 17:46 UTC, sarahlwelton commented on modules/fts/pages/fts-supported-queries-analytic-query.adoc
> +Analytic queries will take an optional argument from the user for the analyzer to apply over the search criteria prior to search.
```suggestion
Use an Analytic query to apply an analyzer to your search request.
If you don't provide an analyzer, the Search Service uses the analyzer from the Search index. 
```

2023-02-16 17:46 UTC, sarahlwelton commented on modules/fts/pages/fts-supported-queries-analytic-query.adoc
> +If said argument is not provided from the user the analyzer definition is derived from the index definition.
```suggestion

```

2023-02-16 18:21 UTC, jon-strabala commented
@sarahlwelton if this is the same as 7.2 (which I accepted all your changes) can you bulk commit this stuff (I don't know how).

2023-02-16 20:31 UTC, sarahlwelton commented
> @sarahlwelton if this is the same as 7.2 (which I accepted all your changes) can you bulk commit this stuff (I don't know how).

There's still one comment here that I'd like us to resolve, as it was something that was different across the PRs :) Please take a look and comment when you get a chance.

2023-02-23 01:33 UTC, jon-strabala commented on modules/eventing/pages/eventing-api.adoc
> +Reset an Application's statistics.
All eventing functions are an applications that interacts with the DCP feed form KV.  The terms both work.

2023-02-23 14:40 UTC, sarahlwelton commented on modules/eventing/pages/eventing-api.adoc
> +Reset an Application's statistics.
Can we just stick to one or the other for consistency's sake? It would be easiest to make this match your other PRs.

2023-02-23 15:22 UTC, jon-strabala commented on modules/eventing/pages/eventing-api.adoc
> +Reset an Application's statistics.
Sure use "Eventing Function"

2023-02-23 16:46 UTC, sarahlwelton commented on modules/eventing/pages/eventing-api.adoc
> +Reset an Application's statistics.
```suggestion
a| Resets statistics for the provided Eventing Function.
```

2023-02-23 16:46 UTC, sarahlwelton approved these changes

2023-02-23 16:46 UTC, merged