Update best practices with new section.
couchbase/docs-server pull request #3124
Opened 2023-03-28 18:49 UTC by jon-strabala

As per https://issues.couchbase.com/browse/MB-56113 it is important to warn Eventing power uses of corner cases that result in slow undeployment.

2023-03-28 20:02 UTC, sarahlwelton requested changes
Let me know if you just want me to push all these through as a batch and merge!

2023-03-28 20:02 UTC, sarahlwelton commented on modules/eventing/pages/troubleshooting-best-practices.adoc
> +== Why do some of my functions dealing with large datasets take so long to undeploy?
```suggestion
== Why does my function take so long to undeploy?
```

2023-03-28 20:02 UTC, sarahlwelton commented on modules/eventing/pages/troubleshooting-best-practices.adoc
> +Undeployment depends on the size of the Eventing metadata collection (or scratchpad) and not the source or destination.
```suggestion
Undeployment time depends on the size of the Eventing metadata collection or scratchpad, not the source or destination. 
```

2023-03-28 20:02 UTC, sarahlwelton commented on modules/eventing/pages/troubleshooting-best-practices.adoc
> +If any Eventing Function is undeployed on a collection with lots of tombstones the Eventing service has to re-stream these documents for any Eventing Function during undeployment phase.
```suggestion
If you undeploy an Eventing Function on a collection with lots of tombstones, the Eventing service has to re-stream these documents during the undeployment phase. 
```

2023-03-28 20:02 UTC, sarahlwelton commented on modules/eventing/pages/troubleshooting-best-practices.adoc
> +If we have an Eventing function that generates a billion timers which have all fired (relatively quickly say an hour or two) the Eventing Function might take minutes or even an hour to undeploy due t
```suggestion
If you have an Eventing function that generates a billion timers, which have all fired quickly, the Eventing Function might take minutes or an hour to undeploy because of the tombstones remaining on disk. 
```

2023-03-28 20:02 UTC, sarahlwelton commented on modules/eventing/pages/troubleshooting-best-practices.adoc
> +In fact any Eventing Function that shares the same metadata collection will also experience the same slow undeployment.
```suggestion
Any Eventing Function that shares the same metadata collection will also be slow to undeploy.
```

2023-03-28 20:02 UTC, sarahlwelton commented on modules/eventing/pages/troubleshooting-best-practices.adoc
> +Workarounds (best practice) is to have a separate metadata collection for non-timer Eventing Functions which will stream 1024 documents each.
```suggestion
It's recommended to have a separate metadata collection for non-timer Eventing Functions, which will stream 1024 documents each. 
```

2023-03-28 20:02 UTC, sarahlwelton commented on modules/eventing/pages/troubleshooting-best-practices.adoc
> +Eventing Functions that generate a massive amount of timers (1000+/sec.) should use a private collection for metadata and not share this area with other Eventing Functions.
```suggestion
An Eventing Function that generates more than 1000 timers per second should use a private collection for metadata and not share this area with other Eventing Functions.  
```

2023-03-28 20:02 UTC, sarahlwelton commented on modules/eventing/pages/troubleshooting-best-practices.adoc
> +Note the tombstones will remain by default for 3 days unless the Metadata Purge Interval is adjusted.
```suggestion
By default, tombstones remain on disk for 3 days. 
Adjust the Metadata Purge Interval to reduce the number of accumulated tombstones. 
```

2023-03-28 20:02 UTC, sarahlwelton commented on modules/eventing/pages/troubleshooting-best-practices.adoc
> +By lowering the bucket's Metadata Purge Interval  (it can be set to a low as 0.4 hours) the potential for accumulating a massive number of tombstones can be avoided.
```suggestion

```

2023-03-28 20:20 UTC, jon-strabala commented
Your changes look good to me - thanks.

2023-03-29 13:58 UTC, sarahlwelton approved these changes

2023-03-29 13:58 UTC, merged