DOC-11205for71: XDCR binary filter
couchbase/docs-server pull request #3211
Opened 2023-07-06 13:30 UTC by tonyjhillman

2023-07-06 22:41 UTC, hyunjuV requested changes

2023-07-06 22:41 UTC, hyunjuV commented on modules/rest-api/pages/rest-xdcr-create-replication.adoc
> +The `filterBinary` flag is provided only in Couchbase Server Version 7.1.5+, and specifies whether binary documents should be replicated.
filterBinary feature is not in 7.2.0.  It will be in 7.2.1.

2023-07-06 22:41 UTC, hyunjuV commented on modules/rest-api/pages/rest-xdcr-create-replication.adoc
> +* If a filter expression is provided, and the expression refers to the document's body, the document is _not_ replicated.
The statement is incorrect -- the document is replicated.  I tested that this is true in 7.1.4 -- the behavior that is exhibited when filterBinary is false is the same behavior in previous versions where filterBinary option does not exist.
* If a filter expression is provided, and the expression refers to the document's body, the document is replicated.

2023-07-06 22:41 UTC, hyunjuV commented on modules/rest-api/pages/rest-xdcr-create-replication.adoc
> +* If a filter expression is provided, and the expression refers to the document's _key_, or its _xattr_, or to both; and also refers to the document's body; then the expression is applied to the _key
* If a filter expression is provided, and the expression refers to the document's _key_, or its _xattr_, or to both; and also refers to the document's body; then the document is not replicated -- regardless of whether or not the _key_ or the _xattr_ expression permits.

2023-07-06 22:41 UTC, hyunjuV commented on modules/rest-api/pages/rest-xdcr-create-replication.adoc
> +* If a filter expression is provided, and the expression refers to the document's _key_, or its _xattr_, or to both; and also refers to the document's body; then the expression is applied to the _key
I realize that there is no logic to the behavior when filterBinary is false and the scenarios involving when an expression refers to the document's body -- it's just the behavior.  It's the same behavior when filterBinary did not exist -- so, the behavior when filterBinary is false is the same behavior when there was no filterBinary in how binary documents were treated during replication in various scenarios.   So, if you just want the same behavior you always had in previous versions, set filterBinary to false.

The documentation should note that the behavior of filterBinary when it is false is the behavior of XDCR in regards to binary documents in versions where filterBinary option did not exist.

2023-07-07 08:09 UTC, tonyjhillman commented on modules/rest-api/pages/rest-xdcr-create-replication.adoc
> +* If a filter expression is provided, and the expression refers to the document's body, the document is _not_ replicated.
Question: In previous versions, when the expression referred to the key or xattr of a binary document, was the filter applied (and the binary document either replicated or not replicated based on the results)?

2023-07-07 08:19 UTC, hyunjuV commented on modules/rest-api/pages/rest-xdcr-create-replication.adoc
> +* If a filter expression is provided, and the expression refers to the document's body, the document is _not_ replicated.
In previous versions, the behavior would be exactly like when filterBinary is false.
So, if a filter expression exists and contains key or xattr only expression, binary documents are checked against the filter expression and replicated or not replicated based on the key or xattr only expression.

Example:
filter expression: REGEXP_CONTAINS(META().id, "cblogo2")

I insert a binary document with doc id "cblogo2.jpg" -- it's replicated.
I insert a binary document with doc id "cblogo3.jpg" -- it is not replicated.

2023-07-07 08:24 UTC, hyunjuV commented on modules/rest-api/pages/rest-xdcr-create-replication.adoc
> +* If a filter expression is provided, and the expression refers to the document's body, the document is _not_ replicated.
Here's more examples of when filterBinary is false (or no filterBinary as in previous versions):

Example:
filter expression: REGEXP_CONTAINS(META().id, "cblogo") AND REGEXP_CONTAINS(name, "Jane")
I insert a binary document with doc id "cblogo4.jpg" -- it is not replicated

Example: 
filter expression:  REGEXP_CONTAINS(name, "Jane")
I insert a binary document with doc id "cblogo5.jpg" -- binary document is replicated.

2023-08-03 21:42 UTC, nelio2k approved these changes

2023-08-04 02:25 UTC, merged

2023-08-04 04:53 UTC, hyunjuV reviewed
Apologies for the late review.  Looks good.