DOC-6343 Add documentation for running multiple single node containers
couchbase/docs-server pull request #3291
Opened 2023-07-25 13:53 UTC by RayOffiah

https://issues.couchbase.com/browse/DOC-6343

2023-07-25 15:54 UTC, RayOffiah commented
Preview at:

https://rayoffiah.github.io/DOC-6343/server/current/install/getting-started-docker.html#section_deploy_multiple_clusters

2023-07-27 10:34 UTC, tonyjhillman approved these changes

2023-07-27 11:09 UTC, malarky requested changes
Some specific comments, but also wondering if we just need to provide some general guidance on running multiple instances, regardless of how they are clustered.

I *think* (but you should test and verify), if you only want to get to the UI then you can get away with just using the `-p` for 8091 and incrementing the host port.  But, if you actually want an application to connect you'll have to set up alternate addresses for every container after the first one.

If you go over the basics (use of `-p` and alternate addresses), then users can set up as many containers as they want and then cluster them how they want.

2023-07-27 11:09 UTC, malarky commented on modules/install/pages/getting-started-docker.adoc
> +three instances (`db1` and `db2`) of the latest https://hub.docker.com/_/couchbase/[official Couchbase Server container image^] are downloaded
Should be "two instances".

2023-07-27 11:09 UTC, malarky commented on modules/install/pages/getting-started-docker.adoc
> +and installed onto the host computer.
I wouldn't say "installed" when talking about a container.

2023-07-27 11:09 UTC, malarky commented on modules/install/pages/getting-started-docker.adoc
> +. Press btn:[Join Cluster]
I though this section was about running multiple single-node clusters, so shouldn't be any discussion around adding nodes and rebalance.

2023-07-27 11:09 UTC, malarky commented on modules/install/pages/getting-started-docker.adoc
> +$ docker run -d --name db2 -p 9091-9096:8091-8096 -p 12210-12211:11210-11211 couchbase
You can't re-use `12210-12211:11210-11211`, need to find a new set as you did with `8091`.

2023-07-27 11:09 UTC, malarky commented on modules/install/pages/getting-started-docker.adoc
> +$ docker run -d --name db2 -p 9091-9096:8091-8096 -p 12210-12211:11210-11211 couchbase
Also, I don't think a client will be able to connect unless you set up Alternate Addresses.

2023-07-27 13:03 UTC, RayOffiah commented on modules/install/pages/getting-started-docker.adoc
> +three instances (`db1` and `db2`) of the latest https://hub.docker.com/_/couchbase/[official Couchbase Server container image^] are downloaded
Fixed throughout document

2023-09-04 15:32 UTC, merged