DOC-10643 Change code samples to use recommended swapiness of 1
couchbase/docs-server pull request #3302
Opened 2023-08-01 10:05 UTC by RayOffiah

https://issues.couchbase.com/browse/DOC-10643

2023-08-03 06:46 UTC, floriancb requested changes

2023-08-03 06:46 UTC, floriancb commented on modules/install/pages/install-swap-space.adoc
> +sudo sh -c 'echo "#Set swappiness to 1 to avoid swapping" >> /etc/sysctl.conf'
"to avoid swapping" is not quite correct now, with this setting. Maybe instead use "to minimize swapping"

2023-08-03 13:55 UTC, RayOffiah commented on modules/install/pages/install-swap-space.adoc
> +sudo sh -c 'echo "#Set swappiness to 1 to avoid swapping" >> /etc/sysctl.conf'
Yep, that makes sense.

2023-08-04 06:58 UTC, floriancb approved these changes

2023-08-04 09:19 UTC, merged