DOC-11645 Release note for 7.2.3
couchbase/docs-server pull request #3384
Opened 2023-11-10 13:44 UTC by RayOffiah

2023-11-10 14:57 UTC, bfavini commented on modules/release-notes/pages/relnotes.adoc
> +Fix contains upgrades to fix the following advisories:
@RayOffiah I just looked for an example of how we've identified security vulnerabilities in the past. I think you should model this page:  https://docs.couchbase.com/server/7.0/release-notes/relnotes.html#fixed-security-vulnerabilities

2023-11-10 15:45 UTC, bfavini requested changes
Please see my comment

2023-11-13 14:29 UTC, bfavini approved these changes

2023-11-14 18:05 UTC, merged

2023-11-15 04:06 UTC, ritamcouchbase commented on modules/release-notes/pages/relnotes.adoc
> +| DCP nozzle race would leave gomemcached feed running and leak memory. +
This can be rephrased -  If DCP nozzles are started and then stopped in a sequence, there can be leaking gomemcahed leaks. A fix has been provided for feed to be correctly synchronised and closed.