WIP: Initial instructions for Amazon Linux 2
couchbase/docs-server pull request #339
Opened 2019-02-14 22:40 UTC by amarantha-k

2019-02-14 22:41 UTC, amarantha-k commented
@mihirkamdarcouchbase Could you please review the instructions?

2019-02-21 22:44 UTC, amarantha-k commented
Got +1 from Mihir over Slack. 
@eric-schneider Could you review the PR please? Need an approval to merge the updates.

2019-02-25 20:32 UTC, eric-schneider commented on modules/install/pages/amazon-linux2-install.adoc
> +Couchbase Server version 6.0.1 adds support for the Amazon Linux 2 platform.
```suggestion
Instructions for installing Couchbase Server on Amazon Linux 2.
```

2019-02-25 20:32 UTC, eric-schneider commented on modules/install/pages/amazon-linux2-install.adoc
> +
```suggestion

Amazon Linux 2 is supported with Couchbase Server 6.0.1+.
See xref:install-platforms.adoc[Supported Operating Systems] for details.

```

2019-02-25 21:05 UTC, eric-schneider requested changes

2019-02-25 21:05 UTC, eric-schneider commented on modules/install/pages/amazon-linux2-install.adoc
> +Couchbase Server version 6.0.1 adds support for the Amazon Linux 2 platform.
```suggestion
Instructions for installing Couchbase Server on Amazon Linux 2.
```

2019-02-25 21:05 UTC, eric-schneider commented on modules/install/pages/amazon-linux2-install.adoc
> +
```suggestion

Amazon Linux 2 is supported with Couchbase Server 6.0.1+.
See xref:install-platforms.adoc[Supported Operating Systems] for details.

```

2019-02-25 21:55 UTC, amarantha-k commented
@eric-schneider Changes incorporated. Could you take a look and approve?

2019-02-25 21:55 UTC, eric-schneider approved these changes

2019-02-25 21:55 UTC, merged