DOC-11837 multiple backup service issues
couchbase/docs-server pull request #3559
Opened 2024-04-18 20:28 UTC by ggray-cb

Overview of changes in this PR (link leads to preview site).:

- Edits to bring the document in line with our standards.
- Clarified why backup tasks fail under the [Avoiding Task Overlap](https://preview.docs-test.couchbase.com/preview-multiple-backup-service/server/current/learn/services-and-indexes/services/backup-service.html#avoiding-task-overlap) section based on conversation with Matt. 
- Added section of choosing the number of [Backup Service nodes](https://preview.docs-test.couchbase.com/preview-multiple-backup-service/server/current/learn/services-and-indexes/services/backup-service.html#choosing-the-number-of-backup-service-nodes) to address the issue in the ticket (steer users to using a single backup service).

2024-04-19 08:18 UTC, mattyhall requested changes
Thanks Gary - overall a really big improvement 👍

2024-04-19 08:18 UTC, mattyhall commented on modules/learn/pages/services-and-indexes/services/backup-service.adoc
> +You cam list the contents of backed up data and search for specific documents no matter how you back up the data.
```suggestion
You can list the contents of backed up data and search for specific documents no matter how you back up the data.
```

2024-04-19 08:18 UTC, mattyhall commented on modules/learn/pages/services-and-indexes/services/backup-service.adoc
> +Once it has performed an initial full backup, it only performs incremental backups into the repository.
This isn't true - cbbackupmgr can also do a full backup on a non-empty repository using the `--full-backup` flag

2024-04-19 08:18 UTC, mattyhall commented on modules/learn/pages/services-and-indexes/services/backup-service.adoc
> +Selecting `cloud` storage for the backup location requires additional parameters such as the name of the bucket for storing the backup, and the access credentials.
This is decided in repos, not in plans

2024-04-19 08:18 UTC, mattyhall commented on modules/learn/pages/services-and-indexes/services/backup-service.adoc
> +You can still read the backed up data in an  archived repository.
```suggestion
You can still read the backed up data in an archived repository.
```

2024-04-19 08:18 UTC, mattyhall commented on modules/learn/pages/services-and-indexes/services/backup-service.adoc
> +In this configuration, each backup task would have its own repository, removing the possibility of different tasks conflicting.
I'm not sure we should advise this as it is probably overkill and the nodes aren't really assigned to a particular repository, they just take tasks as the tasks appear. I think I would stick to advising multiple backup service nodes for resiliency

2024-04-25 17:58 UTC, bfavini commented on modules/learn/pages/services-and-indexes/services/backup-service.adoc
> +Either way of performing backups lets you perform incremental backups and merge incremental backups to deduplicate data.
Either backup method

2024-04-25 18:00 UTC, bfavini commented on modules/learn/pages/services-and-indexes/services/backup-service.adoc
> +The backup Service only runs a single task at a time.
...runs only a single task...

2024-04-25 18:04 UTC, bfavini approved these changes
small nits...looks good

2024-04-26 14:43 UTC, merged