DOC-12189 cbq in tools package
couchbase/docs-server pull request #3604
Opened 2024-06-12 14:17 UTC by ggray-cb

This PR handles updating the CB Server docs for the addition of the cbq tool into the downloadable packages. I've also edited the page to meet our current documentation standards, and make later updating easier.

[Here's a preview of the changes](https://preview.docs-test.couchbase.com/cbq-in-tools-package/server/current/cli/cli-intro.html).

2024-06-12 15:48 UTC, simon-dew requested changes
Nice use of attributes for the tools version. Some nitpicks

2024-06-12 15:48 UTC, simon-dew commented on modules/cli/pages/cli-intro.adoc
> +:description: The command-line interface (CLI) tools lets you manage and monitor your Couchbase Server installation including clusters, servers, vBuckets, and XDCR.
subject-verb agreement

```suggestion
:description: The command-line interface (CLI) tools let you manage and monitor your Couchbase Server installation including clusters, servers, vBuckets, and XDCR.
```

2024-06-12 15:48 UTC, simon-dew commented on modules/cli/pages/cli-intro.adoc
> +The location of these tools depends on your platform:
Maybe make it clear that this is where you can find the tools after installation?

```suggestion
When you have installed Couchbase Server, you can find the command-line tools in one of the following locations, depending on your your platform:
```

2024-06-12 15:48 UTC, simon-dew commented on modules/cli/pages/cli-intro.adoc
> +* [.path]`C:\Program Files\couchbase\server\bin\tools`.
Remove period for consistency

```suggestion
* [.path]`C:\Program Files\couchbase\server\bin\tools`
```

2024-06-12 15:48 UTC, simon-dew commented on modules/cli/pages/cli-intro.adoc
>  == Managing diagnostics
Title case for consistency with other headings?

```suggestion
== Managing Diagnostics
```

2024-06-14 00:01 UTC, hyunjuV commented on modules/cli/pages/cli-intro.adoc
>  * 7.6.0
* 7.6.0, 7.6.1

2024-06-14 00:04 UTC, hyunjuV approved these changes
Just the one nit picky change:
On line 69, 81:
Instead of 
* 7.6.0
should be
* 7.6.0, 7.6.1

Otherwise looks good.  Thank you for making all the changes.  Will go ahead and approve.

2024-06-17 21:05 UTC, hyunjuV approved these changes

2024-06-18 13:28 UTC, merged