[DOC-9694] FTS nsstats REST API Endpoint Updates
couchbase/docs-server pull request #3715
Opened 2024-10-28 16:11 UTC by sarahlwelton

The point of this PR was to update the page on the nsstats endpoint with proper descriptions of each of the stats returned in the response body. 

I updated the examples and the overall format, and tried to make it clearer how to use this endpoint alongside clarifying what all the stats it returns actually means.

2025-02-05 16:26 UTC, abhinavdangeti commented on modules/rest-api/pages/rest-fts-statistics.adoc
> +a| The total number of gRPC queries rejected because of the memory quota for the Search Service being less than the estimated memory required for merging search results from all partitions for the qu
because of the "available" memory quote for the search service being less ..

2025-02-05 16:26 UTC, abhinavdangeti commented on modules/rest-api/pages/rest-fts-statistics.adoc
> +a| The total number of Search queries rejected because of the memory quota for the Search Service being less than the estimated memory required for merging search results from all partitions for the
Ditto: .. "available" memory quota ..

2025-02-05 16:26 UTC, abhinavdangeti commented
Looking good to me @sarahlwelton, couple comments around a little ambiguity.

2025-02-06 17:06 UTC, abhinavdangeti approved these changes
Thank you @sarahlwelton

2025-02-10 19:41 UTC, Rebecca-Martinez007 requested changes
I noticed the last statistic is missing from the Returned Statistics table. Other than that, I read through it all and it LGTM! 

Let me know if the missing statistic was intentional!

2025-02-10 19:41 UTC, Rebecca-Martinez007 commented on modules/rest-api/pages/rest-fts-statistics.adoc
> +    "vector-sample:vector-sample.color.color-test:total_vectors": 306,
This is not in the table - might be a small mistake or intentional, but I wanted to point it out. 

The Returned Statistics table ends with `BUCKET_NAME:INDEX_NAME:total_term_searchers_finished`.

We might need to include `BUCKET_NAME:INDEX_NAME:total_vectors` and it's description.

2025-02-11 17:10 UTC, sarahlwelton commented on modules/rest-api/pages/rest-fts-statistics.adoc
> +    "vector-sample:vector-sample.color.color-test:total_vectors": 306,
Ah, good shout, let me look at that.

2025-02-11 17:22 UTC, Rebecca-Martinez007 approved these changes
LGTM 🚀

2025-02-11 17:24 UTC, merged