DOC-12728 deprecate windows 10
couchbase/docs-server pull request #3740
Opened 2024-11-25 15:49 UTC by ggray-cb

This PR is for the deprecation announcement for Windows 10.

Added notice of deprecation to the following pages (links lead to preview site): 

* [What's New](https://preview.docs-test.couchbase.com/DOC-12728-deprecate-win-10/server/current/introduction/whats-new.html#supported-platforms).
* [Supported Platforms](https://preview.docs-test.couchbase.com/DOC-12728-deprecate-win-10/server/current/install/install-platforms.html)
* [Release Notes](https://preview.docs-test.couchbase.com/DOC-12728-deprecate-win-10/server/current/release-notes/relnotes.html#deprecated-platforms)

2024-11-26 16:05 UTC, ElliotFrancisHunter commented on modules/install/pages/install-platforms.adoc
> +* 12 "Monterey" (x86-64 and Apple Silicon ARM64) (deprecated in Couchbase Server 7.6)
```suggestion
* 12 "Monterey" (x86-64 and Apple Silicon ARM64) (deprecated in Couchbase Server 7.6.0)
```
For consistency with versioning below

2024-11-26 16:06 UTC, ElliotFrancisHunter requested changes
Tiny niggle but other than that looks great 👍🏼

2024-11-27 16:47 UTC, ElliotFrancisHunter approved these changes

2024-11-29 04:15 UTC, RayOffiah approved these changes
👍🏾

2024-12-03 13:55 UTC, merged