DOC-5240 Add page aliases
couchbase/docs-server pull request #508
Opened 2019-05-21 16:58 UTC by amarantha-k

2019-05-21 17:26 UTC, eric-schneider requested changes

2019-05-21 17:26 UTC, eric-schneider commented on modules/sdk/pages/development-intro.adoc
> +:page-aliases: concepts:application-development, developer-guide:creating-documents,developer-guide:removing-documents
```suggestion
:page-aliases: concepts:application-development,developer-guide:creating-documents,developer-guide:removing-documents
```
Removed space for consistency

2019-06-03 17:25 UTC, amarantha-k commented
@eric-schneider Suggestion accepted. Please review and approve if no further changes.

2019-06-03 18:02 UTC, eric-schneider approved these changes
lgtm

2019-06-27 16:48 UTC, merged