Include term range query in the query-types section
couchbase/docs-server pull request #559
Opened 2019-07-08 18:03 UTC by abhinavdangeti

2019-07-09 17:41 UTC, abhinavdangeti commented
Ping @amarantha-k for review.

2019-07-16 11:17 UTC, amarantha-k requested changes

2019-07-16 11:17 UTC, amarantha-k commented on modules/fts/pages/fts-query-types.adoc
> +By default, the analyzer used for the search text is what was set for the specified field, during index-creation.
during index creation. (no hyphen)

2019-07-16 11:17 UTC, amarantha-k commented on modules/fts/pages/fts-query-types.adoc
> +By default, the analyzer used for the search text is what was set for the specified field, during index-creation.
Just noticed that FTS docs use "index-creation". Unless this is a FTS-specific usage, we should update to "index creation"

2019-07-16 18:26 UTC, abhinavdangeti commented on modules/fts/pages/fts-query-types.adoc
> +By default, the analyzer used for the search text is what was set for the specified field, during index-creation.
Done.

2019-07-16 19:12 UTC, amarantha-k approved these changes
lgtm

2019-07-16 19:13 UTC, merged