DOC-5464 Update Support pricing and subscription info
couchbase/docs-server pull request #656
Opened 2019-08-05 16:12 UTC by amarantha-k

@b33f Please review the change. Once finalized, I'll cherry-pick the updates to 5.5 and mad-hatter branches.

2019-08-06 17:45 UTC, eric-schneider requested changes

2019-08-06 17:45 UTC, eric-schneider commented on modules/introduction/pages/contact-couchbase.adoc
> +Information about pricing and subscription for enterprise support is available at https://www.couchbase.com/subscriptions-and-support.
```suggestion
Information about pricing and subscriptions for enterprise support is available at https://www.couchbase.com/subscriptions-and-support[^].
```

2019-08-07 13:32 UTC, RichardSmedley approved these changes
Not sure left-click is better than click, but it's arguable either way.
LGTM :+1:

2019-08-07 13:36 UTC, amarantha-k commented
Incorporated Eric's suggestions, but don't see an option to mark it reviewed.
Thanks Richard. I'll leave that one for the next time.

2019-08-07 13:36 UTC, merged