Fix links to index join clause
couchbase/docs-server pull request #802
Opened 2019-10-12 07:09 UTC by manishbansal8843

2020-01-21 14:51 UTC, simon-dew requested changes
Change on line 383 needs to be reverted

2020-01-21 14:51 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/selectintro.adoc
> +FROM   (SELECT s1.airportname
Reject this change. In the original example, the inmost subquery selects a single airport in the United States and gives it the alias `t`. The next subquery selects the airport name from `t` and gives it the alias `s1`. The outermost query selects everything from `s1` and gives it the alias `s2`. If we make the change given in this line of the pull request, the query returns an empty object, and the results in lines 391-401 are incorrect.

Revert this line to the original as follows:

```suggestion
FROM   (SELECT t.airportname
```

2020-01-21 14:51 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/selectintro.adoc
> +For details, see xref:n1ql-language-reference/join.adoc#index-join-clause[Index JOIN Clause].
LGTM 👍

2020-03-12 21:49 UTC, amarantha-k approved these changes

2020-03-13 11:08 UTC, simon-dew approved these changes
LGTM 👍

2020-04-02 06:02 UTC, merged